"use client";

import { useEffect, useMemo, useState } from "react";
import { listAuthorisedNetworkGraph } from "../../../cloud/networkRepository";
import { useFirebaseUser } from "../../../firebase/FirebaseProvider";
import { NetworkEdge, NetworkPerson, findShortestPaths } from "../../../shared/networkEngine";

export default function NetworkPath({ projectId }: { projectId: string }) {
  const { user, loading: authLoading } = useFirebaseUser(); const [people, setPeople] = useState<NetworkPerson[]>([]); const [edges, setEdges] = useState<NetworkEdge[]>([]); const [targetId, setTargetId] = useState(""); const [search, setSearch] = useState(""); const [paths, setPaths] = useState<string[][] | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user || user.isAnonymous) return; let alive = true; void listAuthorisedNetworkGraph(projectId, user).then((graph) => { if (alive) { setPeople(graph.people); setEdges(graph.edges); setLoading(false); } }); return () => { alive = false; }; }, [projectId, user]);
  const matches = useMemo(() => people.filter((person) => person.id !== `user_${user?.uid}` && [person.displayName, person.company, person.position].some((value) => value?.toLowerCase().includes(search.toLowerCase()))).slice(0, 20), [people, search, user]);
  const byId = new Map(people.map((person) => [person.id, person]));
  if (authLoading || (Boolean(user && !user.isAnonymous) && loading)) return <main className="cloud-page centred-state">Loading available connection edges…</main>;
  if (!user || user.isAnonymous) return <main className="cloud-page centred-state"><h1>Sign in to find a private Network pathway.</h1><a className="button button-dark" href="/auth">Sign in</a></main>;
  return <main className="cloud-page path-page"><header className="cloud-header"><a className="brand" href={`/network/${projectId}`}><span className="brand-mark"><i /><i /></span><span className="brand-name">Circa<sup>beta</sup></span></a><a href={`/network/${projectId}`}>Back to Network</a></header><section className="path-shell"><div className="path-form paper-panel"><p className="eyebrow"><span /> Deterministic graph search</p><h1>Find a pathway.</h1><label>From<input value="You" disabled /></label><label>To<input value={search} onChange={(e) => { setSearch(e.target.value); setTargetId(""); setPaths(null); }} placeholder="Search a person" /></label>{search && !targetId && <div className="person-matches">{matches.map((person) => <button key={person.id} onClick={() => { setTargetId(person.id); setSearch(person.displayName); }}><strong>{person.displayName}</strong><small>{[person.position, person.company].filter(Boolean).join(" · ")}</small></button>)}</div>}<button className="button button-dark" disabled={!targetId} onClick={() => setPaths(findShortestPaths(edges, `user_${user.uid}`, targetId))}>Find pathway</button></div><div className="path-result">{paths === null ? <div className="quiet-result">Choose a person to see the exact stored pathway—Circa never invents missing relationships.</div> : !paths.length ? <div className="paper-panel no-path"><h2>No known pathway found.</h2><p>Circa could not find a known pathway between these people using the connections available to this Network. This does not mean no connection exists outside the stored data.</p></div> : <>{paths.map((path, index) => <article className="paper-panel pathway-card" key={path.join("-")}><small>{index === 0 ? "Known pathway" : "Alternative shortest pathway"}</small><div>{path.map((id, step) => <div key={id} className="path-person"><span>{byId.get(id)?.displayName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2)}</span><strong>{byId.get(id)?.displayName || "Unknown"}</strong>{step < path.length - 1 && <i>LinkedIn connection ↓</i>}</div>)}</div><p>{path.length - 1} connection steps</p></article>)}</>}</div></section></main>;
}
