export default function PrivacyPage() {
  return <main className="legal-page"><header><a className="brand" href="/"><span className="brand-mark"><i /><i /></span><span className="brand-name">Circa<sup>beta</sup></span></a><a href="/">Back to Circa</a></header><article><p className="eyebrow"><span /> Version 0.9 · 20 August 2026</p><h1>Privacy at Circa</h1><p className="legal-lead">Personal Maps are designed to stay in this browser. Cloud Communities, Networks and optional external Describe are separate, explicit features.</p><aside className="legal-gate"><strong>Pre-release cloud notice</strong><p>Public cloud registration must remain closed until Circa publishes the production controller identity, postal/privacy contact, final processor and transfer details, and has completed qualified UK privacy review. This page documents the implemented product boundary; it is not a substitute for that release approval.</p></aside>
    <h2>Who controls cloud data</h2><p>For a production cloud service, the named Circa operator will be the controller for account and platform data, while a Community organiser may also determine the information they publish. The final legal name and dedicated privacy contact are a launch requirement and must appear here before public cloud data is accepted.</p>
    <h2>What stays on your device</h2><p>Your Personal Workspace—including Personal Projects, People, relationships, notes and local backups—is stored in browser LocalStorage. It is not uploaded by signing in. Use Workspace → Export backup to move or protect it. Clearing site storage or losing the device can remove it.</p>
    <h2>Cloud account and shared spaces</h2><p>If you choose an account, Firebase Authentication processes identity and sign-in details. Firestore stores the account profile, memberships, Community content and proposals, or private Network imports and explicit contributions. Community members see approved information and a limited member directory. Network imports are private by default; other active members can read contributed people and edges only while contribution is on.</p>
    <h2>Information about other people</h2><p>A user may enter or import information about contacts who do not use Circa. Circa uses it only to provide the map, directory or real connection-path feature requested by that user or Community. Circa does not infer sensitive characteristics, rank relationships, build advertising audiences or sell contact data. Users and Community organisers must have an appropriate reason to add and share information about other people.</p>
    <h2>Compose and automated processing</h2><p>Local Describe, Paste List, CSV and deterministic Ask run in the browser. If a signed-in user explicitly selects external Describe, Circa sends the description and limited current-Project structure to its configured provider through Circa’s server. Private notes, email addresses, phone numbers and unrelated Projects are excluded. The provider returns a draft; the user must review and apply it. Circa makes no solely automated legal or similarly significant decisions.</p><p>The external provider must remain disabled until its name, purpose, processing location, contract and retention are recorded here and in Circa’s processor register.</p>
    <h2>Purposes and lawful bases</h2><ul><li>Requested account and cloud features: performance of the service requested by the user.</li><li>Security, abuse prevention and minimal operational records: legitimate interests in keeping Circa and its users safe, subject to a documented balancing review.</li><li>Network contribution and optional external Describe: the user’s explicit choice, which can be withdrawn.</li></ul><p>These bases require final qualified review against the actual operator and launch configuration.</p>
    <h2>Device storage, App Check and analytics</h2><p>Circa uses LocalStorage for the local Workspace, recovery copies and small interface state. Firebase uses browser persistence to keep a chosen cloud account signed in and cache permitted cloud data. App Check/reCAPTCHA may access device and network signals to defend protected requests. Circa’s release source does not enable Firebase Analytics or advertising trackers. Non-essential analytics must not be enabled without a documented storage/access assessment and any required consent.</p>
    <h2>Processors and international transfers</h2><p>Cloud operation uses Firebase/Google Cloud for authentication, database and App Check, and Netlify for hosting and server functions. An external AI provider is optional and disabled unless configured. The production operator must confirm regions, subprocessors, international-transfer mechanism and contracts before launch.</p>
    <h2>How long information is kept</h2><ul><li>Active accounts, memberships and cloud content: while the account or shared space is active.</li><li>Expired/revoked invitations and server rate-limit records: scheduled deletion after 30 days.</li><li>Rejected proposals: 90 days, unless a dispute requires a documented hold.</li><li>Removed membership and minimal moderation records: up to 12 months for safety and accountability, with account identifiers redacted on account deletion where possible.</li><li>Private Network imports: until the user replaces, withdraws, leaves or deletes them.</li><li>Operational backups: no more than 35 days after live deletion, subject to tested restore controls.</li></ul><p>These schedules require production TTL/cleanup jobs and backup configuration before launch.</p>
    <h2>Your choices and rights</h2><p>Account settings provide a cloud-data export, Community/Network leave, contribution withdrawal, owned-space deletion and account deletion. Owners must first transfer or delete spaces they control. Personal Workspace export and deletion stay in the browser. Depending on the processing and lawful basis, people may have rights of access, correction, erasure, restriction, portability and objection, and may complain to the UK Information Commissioner’s Office.</p><p><strong>Your right to object:</strong> you may object to processing based on legitimate interests. The production privacy contact required above must provide the request channel before cloud launch.</p>
    <h2>Age scope</h2><p>Public Circa cloud accounts are limited to people aged 18 or over for the initial beta. Circa must not be marketed to children or schools until an age-appropriate design/Children’s Code assessment, DPIA and suitable defaults are complete. This restriction does not turn a local browser into an age-verification service.</p>
    <h2>Changes</h2><p>Material changes will receive a new version and effective date. Cloud users should be told before a change affects how their information is used.</p>
  </article><footer><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/help">Help</a><a href="/">Circa home</a></footer></main>;
}
