"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { watchMemberProjects } from "../cloud/communityRepository";
import { useFirebaseUser } from "../firebase/FirebaseProvider";
import { signOutOfCirca } from "../firebase/auth";
import { deleteCircaAccount, deleteOwnedCloudProject, downloadCloudExport, leaveCloudProject } from "../cloud/accountLifecycle";

type Membership = { id: string; projectId: string; projectName: string; projectMode: string; role: string; status: string };

export default function AccountPage() {
  const router = useRouter();
  const { user, loading, profileSyncWarning } = useFirebaseUser();
  const [memberships, setMemberships] = useState<Membership[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { if (!user || user.isAnonymous) return; return watchMemberProjects(user.uid, setMemberships, (next) => setError(next instanceof Error ? next.message : "Circa could not load your shared spaces.")); }, [user]);
  const groups = useMemo(() => ({ communities: memberships.filter((item) => item.projectMode === "community"), networks: memberships.filter((item) => item.projectMode === "network") }), [memberships]);
  if (loading) return <main className="cloud-page centred-state" role="status">Opening your Circa…</main>;
  if (!user || user.isAnonymous) return <main className="cloud-page centred-state"><h1>Sign in to see your shared Circa spaces.</h1><a className="button button-dark" href="/auth?returnTo=/account">Sign in</a></main>;
  async function action(key: string, run: () => Promise<unknown>, success: string) { setBusy(key); setError(""); setMessage(""); try { await run(); setMessage(success); } catch (next) { setError(next instanceof Error ? next.message : "Circa could not complete that action."); } finally { setBusy(""); } }
  async function leave(item: Membership) { if (!window.confirm(`Leave ${item.projectName || "this shared space"}? Your private Network import and contribution will be removed.`)) return; await action(`leave-${item.projectId}`, () => leaveCloudProject(item.projectId), "You left the shared space. Refreshing…"); }
  async function deleteOwned(item: Membership) { const confirmation = window.prompt(`Permanently delete this owned space and all of its cloud data? Type exactly: ${item.projectName}`); if (confirmation === null) return; await action(`delete-${item.projectId}`, () => deleteOwnedCloudProject(item.projectId, confirmation), "The owned space was permanently deleted. Refreshing…"); }
  async function deleteAccount() { if (!window.confirm("Delete your Circa cloud account? Export first. Personal maps in this browser are not deleted.")) return; if (window.prompt('Type DELETE to confirm. Owned spaces must be transferred or deleted first.') !== "DELETE") return; await action("delete-account", deleteCircaAccount, "Account deleted."); router.replace("/"); }
  return <main className="cloud-page account-page"><header className="cloud-header"><a className="brand" href="/"><span className="brand-mark"><i /><i /></span><span className="brand-name">Circa<sup>beta</sup></span></a><div className="account-header-actions"><a href="/start">Circa options</a><a href="/privacy">Privacy</a><button onClick={async () => { await signOutOfCirca(); router.replace("/"); }}>Sign out</button></div></header><section className="account-heading"><p className="eyebrow"><span /> Your Circa</p><h1>Welcome back,<br /><em>{user.displayName?.split(/\s+/)[0] || "friend"}.</em></h1><p>Personal maps stay local by default. Shared Communities and Networks live with your account.</p></section>{profileSyncWarning && <p className="cloud-warning" role="status">{profileSyncWarning}</p>}{error && <p className="cloud-warning" role="alert">{error}</p>}{message && <p className="cloud-warning" role="status">{message}</p>}<section className="account-grid"><article className="paper-panel account-local"><small>Local workspace</small><h2>Your private maps</h2><p>Open the browser-based workspace and continue sketching without moving anything to the cloud.</p><a className="button button-paper" href="/?workspace=1">Open personal maps</a></article><AccountCollection title="Communities" items={groups.communities} empty="You have not joined a Community yet." hrefPrefix="/community" actionHref="/community/new" action="Create Community" busy={busy} onLeave={(item) => void leave(item)} onDeleteOwned={(item) => void deleteOwned(item)} /><AccountCollection title="Networks" items={groups.networks} empty="You have not created or joined a Network yet." hrefPrefix="/network" actionHref="/network/new" action="Create Network" busy={busy} onLeave={(item) => void leave(item)} onDeleteOwned={(item) => void deleteOwned(item)} /></section><section className="paper-panel account-data-controls"><small>Your cloud data</small><h2>Export or delete</h2><p>Download the cloud account data Circa can associate with you. Your separate local Personal workspace is exported from its Workspace menu.</p><div><button className="button button-paper" disabled={Boolean(busy)} onClick={() => void action("export", downloadCloudExport, "Cloud export downloaded.")}>{busy === "export" ? "Preparing…" : "Download cloud export"}</button><button className="button danger-button" disabled={Boolean(busy)} onClick={() => void deleteAccount()}>{busy === "delete-account" ? "Deleting…" : "Delete cloud account"}</button></div><p className="quiet">Account deletion is blocked while you own a Community or Network. Transfer ownership inside that space, or permanently delete it here first.</p></section></main>;
}

function AccountCollection({ title, items, empty, hrefPrefix, actionHref, action, busy, onLeave, onDeleteOwned }: { title: string; items: Membership[]; empty: string; hrefPrefix: string; actionHref: string; action: string; busy: string; onLeave: (item: Membership) => void; onDeleteOwned: (item: Membership) => void }) {
  return <article className="paper-panel account-collection"><header><div><small>Shared with your account</small><h2>{title}</h2></div><a href={actionHref}>{action} +</a></header>{items.length ? <div className="account-rows">{items.map((item) => <div className="account-membership-row" key={item.id}><a href={`${hrefPrefix}/${item.projectId}`}><span><strong>{item.projectName || `Untitled ${title.slice(0, -1)}`}</strong><small>{item.role === "owner" ? "Owner" : item.role === "admin" ? "Admin" : "Member"}</small></span><i>Open →</i></a>{item.role === "owner" ? <button className="danger-link" disabled={Boolean(busy)} onClick={() => onDeleteOwned(item)}>{busy === `delete-${item.projectId}` ? "Deleting…" : "Delete owned space"}</button> : <button className="danger-link" disabled={Boolean(busy)} onClick={() => onLeave(item)}>{busy === `leave-${item.projectId}` ? "Leaving…" : `Leave ${title.slice(0, -1)}`}</button>}</div>)}</div> : <p className="quiet">{empty}</p>}</article>;
}
