"use client";

import { useEffect, useMemo, useState } from "react";
import { createInvitation, getCloudProject, getMembership, watchInvitations, watchMembers } from "../../cloud/communityRepository";
import { getNetworkContribution, listAuthorisedNetworkGraph, setNetworkContribution } from "../../cloud/networkRepository";
import type { CloudProject, CommunityMember, PublicInvite } from "../../cloud/types";
import { useFirebaseUser } from "../../firebase/FirebaseProvider";
import { NetworkEdge, NetworkPerson, answerNetworkQuestion } from "../../shared/networkEngine";

type View = "overview" | "people" | "members";

export default function NetworkDashboard({ projectId }: { projectId: string }) {
  const { user, loading: authLoading } = useFirebaseUser(); const [project, setProject] = useState<CloudProject | null>(null); const [membership, setMembership] = useState<CommunityMember | null>(null); const [members, setMembers] = useState<CommunityMember[]>([]); const [invites, setInvites] = useState<PublicInvite[]>([]); const [people, setPeople] = useState<NetworkPerson[]>([]); const [edges, setEdges] = useState<NetworkEdge[]>([]); const [complete, setComplete] = useState(false); const [query, setQuery] = useState(""); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [share, setShare] = useState(false); const [confirmShare, setConfirmShare] = useState(false); const [view, setView] = useState<View>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { if (!user || user.isAnonymous) return; let alive = true; void Promise.all([getCloudProject(projectId), getMembership(projectId, user.uid)]).then(async ([nextProject, nextMembership]) => { if (!alive) return; setProject(nextProject); setMembership(nextMembership); if (!nextProject || !nextMembership || nextMembership.status !== "active") { setLoading(false); return; } const [graph, sharing] = await Promise.all([listAuthorisedNetworkGraph(projectId, user), getNetworkContribution(projectId, user.uid)]); if (alive) { setPeople(graph.people); setEdges(graph.edges); setComplete(graph.complete); setShare(sharing); setLoading(false); } }).catch((next) => { if (alive) { setError(next instanceof Error ? next.message : "Circa could not open this Network."); setLoading(false); } }); return () => { alive = false; }; }, [projectId, user]);
  useEffect(() => { if (!membership || membership.status !== "active") return; let active = true; const memberStop = watchMembers(projectId, (next) => { void Promise.all(next.map(async (member) => ({ ...member, contributionEnabled: await getNetworkContribution(projectId, member.uid) }))).then((withContributions) => { if (active) setMembers(withContributions); }); }); const inviteStop = watchInvitations(projectId, setInvites); return () => { active = false; memberStop(); inviteStop(); }; }, [membership, projectId]);
  const filtered = useMemo(() => { const normal = query.toLowerCase().trim(); return people.filter((person) => !normal || [person.displayName, person.company, person.position].some((value) => value?.toLowerCase().includes(normal))).slice(0, 100); }, [people, query]);
  const companies = useMemo(() => [...people.reduce((map, person) => { if (person.company) map.set(person.company, (map.get(person.company) || 0) + 1); return map; }, new Map<string, number>())].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, 8), [people]);
  if (authLoading || (Boolean(user && !user.isAnonymous) && loading)) return <main className="cloud-page centred-state" role="status">Opening your Network…</main>;
  if (!user || user.isAnonymous) return <main className="cloud-page centred-state"><h1>Create your Circa account to import and protect your network.</h1><a className="button button-dark" href={`/auth?returnTo=/network/${projectId}`}>Create account or sign in</a></main>;
  if (!project || !membership || membership.status !== "active") return <main className="cloud-page centred-state"><h1>This Network is private.</h1><p>{error || "You do not have access to this Network."}</p></main>;
  const selfId = `user_${user.uid}`; const contributionByUid = new Map(members.map((member) => [member.uid, member.contributionEnabled]));
  return <main className="cloud-page network-page"><header className="community-header"><a className="brand" href="/"><span className="brand-mark"><i /><i /></span><span className="brand-name">Circa<sup>beta</sup></span></a><div><span className="saved-dot" /> {complete ? "Complete Network loaded" : "Loading Network"}</div><a href="/account">Your Circa</a></header><section className="network-heading"><div><p className="eyebrow"><span /> Professional relationships</p><h1>{project.name}</h1><p>{project.description}</p></div><div className="network-stat"><strong>{Math.max(0, people.length - 1)}</strong><span>connections available</span></div></section><nav className="network-tabs"><button className={view === "overview" ? "active" : ""} onClick={() => setView("overview")}>Overview</button><button className={view === "people" ? "active" : ""} onClick={() => setView("people")}>People</button><button className={view === "members" ? "active" : ""} onClick={() => setView("members")}>Members</button></nav>
    {view === "overview" && <><section className="network-actions"><a className="button button-dark" href={`/network/${projectId}/path`}>Find a pathway</a><a className="button button-paper" href={`/network/${projectId}/import`}>Import newer data</a></section><section className="network-overview"><article className="paper-panel network-path-hero"><p className="eyebrow"><span /> Known pathways</p><h2>Find how people may be connected.</h2><p>Circa follows only real stored edges contributed by consenting Network members.</p><a className="button button-dark" href={`/network/${projectId}/path`}>Choose someone</a></article><article className="paper-panel network-ask"><h2>Ask this Network</h2><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="How am I connected to Maya?" /><button className="button button-paper" onClick={() => setAnswer(answerNetworkQuestion(question, people, edges, selfId).answer)}>Ask Circa</button>{answer && <p role="status">{answer}</p>}</article><article className="paper-panel company-list"><h2>Companies</h2>{companies.map(([company, count]) => <div key={company}><span>{company}</span><strong>{count}</strong></div>)}{!companies.length && <p className="quiet">Companies appear after import.</p>}</article><article className="paper-panel contribution-control"><h2>Your contribution</h2><strong className={share ? "contribution-on" : "contribution-off"}>{share ? "ON" : "OFF"}</strong><p>Importing is private. Contribution is separate and reversible; members may discover pathways through the edges you share.</p>{!share && !confirmShare && <button onClick={() => setConfirmShare(true)}>Contribute my Network</button>}{confirmShare && <div className="consent-box"><strong>Share real connection edges?</strong><p>Your private email fields and notes never become project-visible.</p><button onClick={async () => { await setNetworkContribution(projectId, user, true); setShare(true); setConfirmShare(false); }}>Confirm contribution</button><button onClick={() => setConfirmShare(false)}>Cancel</button></div>}{share && <button onClick={async () => { await setNetworkContribution(projectId, user, false); setShare(false); }}>Stop contributing</button>}</article></section></>}
    {view === "people" && <section className="network-grid single"><article className="paper-panel network-directory"><header><div><h2>People</h2><p>Search by name, company or position. The complete authorised dataset is cursor-paginated, never silently truncated.</p></div><label>Search people<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, company or position" /></label></header><div className="network-rows">{filtered.map((person) => <div key={person.id}><span>{person.displayName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2)}</span><div><strong>{person.displayName}{person.id === selfId ? " (you)" : ""}</strong><small>{[person.position, person.company].filter(Boolean).join(" · ") || "LinkedIn connection"}</small></div>{person.linkedinProfileUrl && <a href={person.linkedinProfileUrl} target="_blank" rel="noreferrer">Profile</a>}</div>)}{!filtered.length && <p className="quiet">No matching person.</p>}</div></article></section>}
    {view === "members" && <section className="network-members"><article className="paper-panel"><header><div><p className="eyebrow"><span /> Shared Network</p><h2>Members</h2></div>{membership.role === "owner" && <button className="button button-paper" onClick={() => void createInvitation(project, user.uid, { label: "Network member invitation" })}>Invite to Network</button>}</header>{members.filter((member) => member.status === "active").map((member) => <div className="network-member-row" key={member.uid}><span>{member.displayName?.slice(0, 1).toUpperCase()}</span><div><strong>{member.displayName}</strong><small>{member.role === "owner" ? "Owner" : "Member"}</small></div><i>Network contribution {member.uid === user.uid ? (share ? "ON" : "OFF") : contributionByUid.get(member.uid) ? "ON" : "OFF"}</i></div>)}</article><aside className="paper-panel"><h2>Invitation</h2>{invites[0] ? <><strong>{invites[0].code}</strong><p>Share this code with a person you trust. Joining never shares their imported connections.</p><button onClick={() => void navigator.clipboard.writeText(invites[0].code)}>Copy code</button></> : <p className="quiet">The Network owner can create an invitation.</p>}</aside></section>}
  </main>;
}
