"use client";

import QRCode from "qrcode";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { addPublishedItem, addPublishedList, createInvitation, createReminder, deletePublishedItem, getCloudProject, removeMember, revokeInvitation, reviewProposal, submitProposal, updateCommunitySettings, updateMemberRole, updatePublishedItem, watchCommunityItems, watchCommunityLists, watchInvitations, watchMembers, watchMembership, watchProposals, watchReminders } from "../../cloud/communityRepository";
import type { CloudProject, CommunityItem, CommunityList, CommunityListType, CommunityMember, EditProposal, PublicInvite } from "../../cloud/types";
import { disconnectWhatsApp, getWhatsAppIntegrationStatus, startWhatsAppLink, updateWhatsAppPreferences } from "../../cloud/whatsappClient";
import { useFirebaseUser } from "../../firebase/FirebaseProvider";
import { PublishedCommunityRecord, queryCommunity } from "../../shared/communityQueryEngine";

type Tab = "home" | "directory" | "events" | "ask" | "suggestions" | "whatsapp" | "manage";
type ItemDraft = Partial<CommunityItem>;
const emptyItem: ItemDraft = { title: "", details: "", category: "", itemType: "directory", phone: "", email: "", website: "", address: "", notes: "", startDate: "", startTime: "", endTime: "", location: "", binType: "", schedule: { type: "fortnightly", firstCollectionDate: "", intervalWeeks: 2 }, enabled: true };

function Mark() { return <span className="brand-mark" aria-hidden="true"><i /><i /></span>; }
function dateLabel(value: unknown) { if (!value) return ""; const candidate = value as { toDate?: () => Date }; const date = typeof candidate.toDate === "function" ? candidate.toDate() : new Date(String(value)); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(date) : ""; }

export default function CommunityClient({ projectId }: { projectId: string }) {
  const { user, loading: authLoading } = useFirebaseUser();
  const [project, setProject] = useState<CloudProject | null>(null); const [member, setMember] = useState<CommunityMember | null>(null); const [members, setMembers] = useState<CommunityMember[]>([]); const [lists, setLists] = useState<CommunityList[]>([]); const [items, setItems] = useState<Record<string, CommunityItem[]>>({});
  const [proposals, setProposals] = useState<EditProposal[]>([]); const [invites, setInvites] = useState<PublicInvite[]>([]); const [reminders, setReminders] = useState<Array<{ id: string; [key: string]: unknown }>>([]); const [tab, setTab] = useState<Tab>("home"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const canReview = member?.role === "owner" || member?.role === "admin";

  useEffect(() => { if (!user) return; let alive = true; void getCloudProject(projectId).then((next) => { if (alive) setProject(next); }).catch((next) => { if (alive) setError(next instanceof Error ? next.message : "Community unavailable."); }); const unsubscribe = watchMembership(projectId, user.uid, (next) => { if (!alive) return; setMember(next); setLoading(false); }); return () => { alive = false; unsubscribe(); }; }, [projectId, user]);
  useEffect(() => { if (!member || member.status !== "active") return; return watchCommunityLists(projectId, setLists); }, [member, projectId]);
  useEffect(() => { if (!member || member.status !== "active") return; const stops = lists.map((list) => watchCommunityItems(projectId, list.id, (next) => setItems((current) => ({ ...current, [list.id]: next })))); return () => stops.forEach((stop) => stop()); }, [member, projectId, lists]);
  useEffect(() => { if (!user || !member || member.status !== "active") return; return watchProposals(projectId, user.uid, Boolean(canReview), setProposals); }, [canReview, member, projectId, user]);
  useEffect(() => { if (!canReview) return; const stops = [watchMembers(projectId, setMembers), watchInvitations(projectId, setInvites), watchReminders(projectId, setReminders)]; return () => stops.forEach((stop) => stop()); }, [canReview, projectId]);

  const records = useMemo(() => lists.flatMap((list) => (items[list.id] || []).map((item): PublishedCommunityRecord => ({ listId: list.id, listTitle: list.title, itemId: item.id, title: item.title, details: item.details, category: item.category, itemType: item.itemType || list.listType, phone: item.phone, email: item.email, url: item.url || item.website, website: item.website, address: item.address, notes: item.notes, date: item.date, startDate: item.startDate, startTime: item.startTime, endTime: item.endTime, location: item.location, binType: item.binType, schedule: item.schedule, timezone: project?.timezone, enabled: item.enabled }))), [items, lists, project?.timezone]);

  if (authLoading || (Boolean(user) && loading)) return <main className="cloud-page centred-state" role="status">Opening this Community…</main>;
  if (!user) return <main className="cloud-page centred-state"><h1>Sign in to return to this Community.</h1><p>If you have an invitation, reopen it to join first.</p><a className="button button-dark" href={`/auth?returnTo=/community/${projectId}`}>Sign in</a></main>;
  if (!member || member.status !== "active") return <main className="cloud-page centred-state"><h1>This Community is private.</h1><p>Use an active invitation link or code to join.</p><a className="button button-paper" href="/join">Enter a Community code</a></main>;
  if (!project) return <main className="cloud-page centred-state"><h1>Community unavailable.</h1><p>{error || "Circa could not open this Community."}</p></main>;

  const tabs: Array<[Tab, string]> = [["home", "Home"], ["directory", "Directory"], ["events", "Events"], ["ask", "Ask"], ["suggestions", "Suggestions"], ["whatsapp", "WhatsApp"], ...(canReview ? [["manage", proposals.length ? `Manage (${proposals.length})` : "Manage"] as [Tab, string]] : [])];
  return <main className="cloud-page community-page"><header className="community-header"><a className="brand" href="/"><Mark /><span className="brand-name">Circa<sup>beta</sup></span></a><div><span className="saved-dot" /> Community data live</div><a href="/account">Your Circa</a></header><section className="community-title"><div><p className="eyebrow"><span /> Circa Community</p><h1>{project.name}</h1><p>{project.location}{project.location && project.description ? " - " : ""}{project.description}</p></div>{canReview && <a className="role-link" href="#community-manage" onClick={(event) => { event.preventDefault(); setTab("manage"); }}>Community {member.role}</a>}</section><nav className="community-tabs" aria-label="Community sections">{tabs.map(([value, label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}</button>)}</nav>
    {tab === "home" && <CommunityHome project={project} lists={lists} items={items} records={records} onTab={setTab} />}
    {tab === "directory" && <DirectoryView lists={lists.filter((list) => list.listType !== "event" && list.listType !== "bin")} items={items} user={user} projectId={projectId} canReview={Boolean(canReview)} />}
    {tab === "events" && <EventsView lists={lists} items={items} user={user} projectId={projectId} canReview={Boolean(canReview)} />}
    {tab === "ask" && <CommunityAsk project={project} records={records} />}
    {tab === "suggestions" && <SuggestionCentre projectId={projectId} lists={lists} items={items} user={user} proposals={canReview ? [] : proposals} />}
    {tab === "whatsapp" && <WhatsAppPanel projectId={projectId} />}
    {tab === "manage" && canReview && <ManageView project={project} lists={lists} proposals={proposals} members={members} invites={invites} reminders={reminders} userId={user.uid} />}
  </main>;
}

function CommunityHome({ project, lists, items, records, onTab }: { project: CloudProject; lists: CommunityList[]; items: Record<string, CommunityItem[]>; records: PublishedCommunityRecord[]; onTab: (tab: Tab) => void }) {
  const tomorrow = queryCommunity("What bin is tomorrow?", records, { timezone: project.timezone }); const nextEvent = queryCommunity("What is the next event?", records, { timezone: project.timezone });
  return <section className="community-home"><header><p>{new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", timeZone: project.timezone || "Europe/London" }).format(new Date())}</p><h2>Good {new Date().getHours() < 12 ? "morning" : new Date().getHours() < 18 ? "afternoon" : "evening"}.</h2></header><div className="community-home-grid"><article className="paper-panel home-highlight"><small>Tomorrow&apos;s collection</small><h3>{tomorrow.itemIds.length ? tomorrow.answer.split(" is collected")[0] : "No collection found"}</h3><p>{tomorrow.answer}</p></article><article className="paper-panel home-upcoming"><small>Upcoming</small><h3>{nextEvent.itemIds.length ? nextEvent.answer.split(" is ")[0] : "Nothing published yet"}</h3><p>{nextEvent.answer}</p></article></div><section className="community-explore"><header><h2>Explore</h2><button onClick={() => onTab("directory")}>View directory →</button></header><div>{lists.map((list) => <button key={list.id} onClick={() => onTab(list.listType === "event" ? "events" : "directory")}><span>{list.title}</span><strong>{(items[list.id] || []).length}</strong><small>{list.description}</small></button>)}</div></section><article className="paper-panel home-ask"><div><small>Ask Circa</small><h2>Ask anything about this Community.</h2><p>Answers come only from approved information.</p></div><button className="button button-dark" onClick={() => onTab("ask")}>Ask Circa</button></article></section>;
}

function DirectoryView({ lists, items, user, projectId, canReview }: { lists: CommunityList[]; items: Record<string, CommunityItem[]>; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; projectId: string; canReview: boolean }) {
  if (!lists.length) return <section className="community-empty"><h2>No directory sections yet.</h2><p>A Community admin can add the first approved information.</p></section>;
  return <section className="community-lists">{lists.map((list) => <article className="community-list paper-panel" key={list.id}><header><small>{list.listType}</small><h2>{list.title}</h2>{list.description && <p>{list.description}</p>}</header><div>{(items[list.id] || []).map((item) => <CommunityItemCard key={item.id} item={item} listId={list.id} projectId={projectId} user={user} canReview={canReview} />)}{!(items[list.id] || []).length && <p className="quiet">Nothing published here yet.</p>}</div></article>)}</section>;
}

function EventsView({ lists, items, user, projectId, canReview }: { lists: CommunityList[]; items: Record<string, CommunityItem[]>; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; projectId: string; canReview: boolean }) {
  const eventLists = lists.filter((list) => list.listType === "event" || (items[list.id] || []).some((item) => item.itemType === "event"));
  return <section className="events-board"><header><p className="eyebrow"><span /> What&apos;s coming up</p><h2>Community events.</h2></header>{eventLists.flatMap((list) => (items[list.id] || []).map((item) => <CommunityItemCard key={item.id} item={item} listId={list.id} projectId={projectId} user={user} canReview={canReview} />)).sort((a, b) => String(a.props.item.startDate || "").localeCompare(String(b.props.item.startDate || "")))}</section>;
}

function CommunityItemCard({ item, listId, projectId, user, canReview }: { item: CommunityItem; listId: string; projectId: string; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; canReview: boolean }) {
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<ItemDraft>(item); const [message, setMessage] = useState("");
  const fields = [["Phone", item.phone], ["Email", item.email], ["Website", item.website || item.url], ["Address", item.address], ["Opening", item.openingInformation], ["Date", item.startDate || item.date], ["Time", [item.startTime, item.endTime].filter(Boolean).join(" - ")], ["Location", item.location], ["Notes", item.notes]].filter(([, value]) => Boolean(value));
  return <div className="community-item"><h3>{item.title}</h3>{item.details && <p>{item.details}</p>}<dl>{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{label === "Website" ? <a href={String(value)} target="_blank" rel="noreferrer">Open website</a> : label === "Email" ? <a href={`mailto:${value}`}>{value}</a> : label === "Phone" ? <a href={`tel:${value}`}>{value}</a> : value}</dd></div>)}</dl>{editing && <ItemFields item={draft} onChange={setDraft} compact />}{editing ? <div className="item-actions"><button onClick={async () => { if (canReview) { await updatePublishedItem(projectId, listId, item.id, draft); setMessage("Published item updated."); } else { await submitProposal(user, projectId, { listId, itemId: item.id, operation: "update", proposedItem: { ...item, ...draft }, reason: "Suggested correction", }); setMessage("Correction submitted for admin review."); } setEditing(false); }}>{canReview ? "Save changes" : "Submit correction"}</button><button onClick={() => setEditing(false)}>Cancel</button></div> : <div className="item-actions"><button onClick={() => setEditing(true)}>{canReview ? "Edit" : "Suggest a correction"}</button>{canReview && <button onClick={async () => { if (window.confirm(`Delete ${item.title}? This cannot be undone.`)) await deletePublishedItem(projectId, listId, item.id); }}>Delete</button>}{!canReview && <button onClick={async () => { const reason = window.prompt("Why should this be removed?"); if (reason) { await submitProposal(user, projectId, { listId, itemId: item.id, operation: "delete", proposedItem: null, reason }); setMessage("Removal suggestion submitted for review."); } }}>Suggest removal</button>}</div>}{message && <small role="status">{message}</small>}</div>;
}

function CommunityAsk({ project, records }: { project: CloudProject; records: PublishedCommunityRecord[] }) {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState("");
  return <section className="paper-panel community-ask"><p className="eyebrow"><span /> Approved information only</p><h2>Ask this Community.</h2><p>Circa uses specialised handlers for collections, events, directory entries and contacts. Pending suggestions never appear here.</p><label>Your question<textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about an event, collection or local contact…" /></label><div className="ask-chips"><button onClick={() => setQuestion("What bin is tomorrow?")}>What bin is tomorrow?</button><button onClick={() => setQuestion("What is the next event?")}>What is the next event?</button><button onClick={() => setQuestion("Do we have a plumber?")}>Do we have a plumber?</button></div><button className="button button-dark" disabled={!question.trim()} onClick={() => setAnswer(queryCommunity(question, records, { timezone: project.timezone }).answer)}>Ask Circa</button>{answer && <pre className="community-answer" role="status">{answer}</pre>}</section>;
}

function SuggestionCentre({ projectId, lists, items, user, proposals }: { projectId: string; lists: CommunityList[]; items: Record<string, CommunityItem[]>; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; proposals: EditProposal[] }) {
  const [operation, setOperation] = useState<"create" | "update" | "delete">("create"); const [listId, setListId] = useState(""); const [itemId, setItemId] = useState(""); const [draft, setDraft] = useState<ItemDraft>(emptyItem); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const selectedList = listId || lists[0]?.id || ""; const selectedItem = (items[selectedList] || []).find((item) => item.id === itemId);
  async function submit(event: FormEvent) { event.preventDefault(); if (!selectedList || (operation !== "create" && !selectedItem)) return; setBusy(true); setMessage(""); try { await submitProposal(user, projectId, { listId: selectedList, itemId: selectedItem?.id || "", operation, proposedItem: operation === "delete" ? null : { ...emptyItem, ...draft, order: selectedItem?.order || Date.now(), schemaVersion: 2 } as Omit<CommunityItem, "id">, reason }); setDraft(emptyItem); setItemId(""); setReason(""); setMessage("Suggestion submitted. Published information has not changed; an admin will review it."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not submit that suggestion."); } finally { setBusy(false); } }
  return <section className="suggestion-layout"><form className="paper-panel community-form" onSubmit={submit}><p className="eyebrow"><span /> Member contribution</p><h2>Suggest a change.</h2><label>Type<select value={operation} onChange={(event) => { const next = event.target.value as typeof operation; setOperation(next); setItemId(""); setDraft(emptyItem); }}><option value="create">Addition</option><option value="update">Correction</option><option value="delete">Removal</option></select></label><label>Section<select value={selectedList} onChange={(event) => { setListId(event.target.value); setItemId(""); setDraft(emptyItem); }}>{lists.map((list) => <option value={list.id} key={list.id}>{list.title}</option>)}</select></label>{operation !== "create" && <label>Published item<select required value={itemId} onChange={(event) => { const nextId = event.target.value; setItemId(nextId); const nextItem = (items[selectedList] || []).find((item) => item.id === nextId); if (nextItem) setDraft(nextItem); }}><option value="">Choose an item</option>{(items[selectedList] || []).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}{operation !== "delete" && <ItemFields item={draft} onChange={setDraft} />}<label>Reason <small>{operation === "delete" ? "required" : "optional"}</small><textarea required={operation === "delete"} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="What should the admin know?" /></label><button className="button button-dark" disabled={busy || !lists.length}>{busy ? "Submitting…" : "Submit for review"}</button>{message && <p role="status" className="form-message">{message}</p>}</form><aside className="paper-panel proposal-history"><h2>My Suggestions</h2>{proposals.map((proposal) => <div key={proposal.id}><span><strong>{proposal.proposedItem?.title || proposal.currentItem?.title || "Community item"}</strong><small>{proposal.operation === "create" ? "Addition" : proposal.operation === "update" ? "Correction" : "Removal"}</small></span><i className={`status-${proposal.status}`}>{proposal.status}</i></div>)}{!proposals.length && <p className="quiet">Your suggestions and review status will appear here.</p>}</aside></section>;
}

function ItemFields({ item, onChange, compact = false }: { item: ItemDraft; onChange: (item: ItemDraft) => void; compact?: boolean }) {
  const set = (key: keyof CommunityItem, value: unknown) => onChange({ ...item, [key]: value });
  return <div className={compact ? "item-fields compact" : "item-fields"}><label>Name / title<input required value={item.title || ""} onChange={(event) => set("title", event.target.value)} /></label><label>Description<textarea value={item.details || ""} onChange={(event) => set("details", event.target.value)} /></label><div className="field-pair"><label>Phone<input value={item.phone || ""} onChange={(event) => set("phone", event.target.value)} /></label><label>Email<input type="email" value={item.email || ""} onChange={(event) => set("email", event.target.value)} /></label></div><label>Website<input type="url" value={item.website || item.url || ""} onChange={(event) => set("website", event.target.value)} /></label><label>Address<input value={item.address || ""} onChange={(event) => set("address", event.target.value)} /></label><label>Notes<textarea value={item.notes || ""} onChange={(event) => set("notes", event.target.value)} /></label>{item.itemType === "event" && <><div className="field-pair"><label>Date<input type="date" value={item.startDate || ""} onChange={(event) => set("startDate", event.target.value)} /></label><label>Start time<input type="time" value={item.startTime || ""} onChange={(event) => set("startTime", event.target.value)} /></label></div><label>Location<input value={item.location || ""} onChange={(event) => set("location", event.target.value)} /></label></>}{item.itemType === "bin" && <><label>Bin type<input value={item.binType || ""} onChange={(event) => set("binType", event.target.value)} placeholder="Recycling, general waste…" /></label><div className="field-pair"><label>Schedule<select value={item.schedule?.type || "fortnightly"} onChange={(event) => set("schedule", { ...(item.schedule || { firstCollectionDate: "" }), type: event.target.value })}><option value="once">Once</option><option value="weekly">Weekly</option><option value="fortnightly">Every 2 weeks</option><option value="custom">Custom</option></select></label><label>First collection<input type="date" value={item.schedule?.firstCollectionDate || ""} onChange={(event) => set("schedule", { ...(item.schedule || { type: "fortnightly" }), firstCollectionDate: event.target.value })} /></label></div></>}</div>;
}

function ManageView({ project, lists, proposals, members, invites, reminders, userId }: { project: CloudProject; lists: CommunityList[]; proposals: EditProposal[]; members: CommunityMember[]; invites: PublicInvite[]; reminders: Array<{ id: string; [key: string]: unknown }>; userId: string }) {
  const [section, setSection] = useState<"content" | "review" | "members" | "invites" | "reminders">("content");
  return <section className="manage-shell" id="community-manage"><nav className="manage-nav">{(["content", "review", "members", "invites", "reminders"] as const).map((value) => <button className={section === value ? "active" : ""} onClick={() => setSection(value)} key={value}>{value === "review" ? `Review (${proposals.length})` : value[0].toUpperCase() + value.slice(1)}</button>)}</nav>{section === "content" && <ContentManager project={project} lists={lists} />}{section === "review" && <ReviewQueue project={project} proposals={proposals} userId={userId} />}{section === "members" && <MembersManager project={project} members={members} userId={userId} />}{section === "invites" && <InvitationsManager project={project} invites={invites} userId={userId} />}{section === "reminders" && <RemindersManager project={project} reminders={reminders} />}</section>;
}

function ContentManager({ project, lists }: { project: CloudProject; lists: CommunityList[] }) {
  const [sectionTitle, setSectionTitle] = useState(""); const [sectionType, setSectionType] = useState<CommunityListType>("directory"); const [listId, setListId] = useState(""); const [draft, setDraft] = useState<ItemDraft>(emptyItem); const [message, setMessage] = useState(""); const target = listId || lists[0]?.id || ""; const type = lists.find((list) => list.id === target)?.listType || "custom";
  const effectiveDraft = { ...draft, itemType: type };
  return <section className="admin-grid"><article className="paper-panel admin-publish"><p className="eyebrow"><span /> Directory structure</p><h2>Add a section.</h2><form className="community-form" onSubmit={async (event) => { event.preventDefault(); await addPublishedList(project.id, sectionTitle, sectionType); setSectionTitle(""); setMessage("Section added."); }}><label>Name<input required value={sectionTitle} onChange={(event) => setSectionTitle(event.target.value)} /></label><label>Type<select value={sectionType} onChange={(event) => setSectionType(event.target.value as CommunityListType)}><option value="directory">Directory</option><option value="event">Event</option><option value="bin">Bin collection</option><option value="school">School</option><option value="contact">Contact</option><option value="custom">Custom</option></select></label><button className="button button-paper">Add section</button></form></article><article className="paper-panel admin-publish"><p className="eyebrow"><span /> Published information</p><h2>Publish an item.</h2><form className="community-form" onSubmit={async (event) => { event.preventDefault(); if (!target) return; await addPublishedItem(project.id, target, effectiveDraft); setDraft({ ...emptyItem, itemType: type }); setMessage("Published item added."); }}><label>Section<select value={target} onChange={(event) => { setListId(event.target.value); setDraft(emptyItem); }}>{lists.map((list) => <option key={list.id} value={list.id}>{list.title}</option>)}</select></label><ItemFields item={effectiveDraft} onChange={setDraft} /><button className="button button-dark">Publish item</button>{message && <p role="status">{message}</p>}</form></article></section>;
}

function ReviewQueue({ project, proposals, userId }: { project: CloudProject; proposals: EditProposal[]; userId: string }) {
  const [notes, setNotes] = useState<Record<string, string>>({});
  return <section className="review-list"><header><p className="eyebrow"><span /> Review queue</p><h2>Member suggestions.</h2></header>{proposals.map((proposal) => { const current = proposal.currentItem || null; const proposed = proposal.proposedItem || null; const keys = [...new Set([...Object.keys(current || {}), ...Object.keys(proposed || {})])].filter((key) => !["id", "schemaVersion", "order"].includes(key) && JSON.stringify((current as unknown as Record<string, unknown>)?.[key]) !== JSON.stringify((proposed as unknown as Record<string, unknown>)?.[key])); return <article className="paper-panel proposal-diff" key={proposal.id}><header><div><small>{proposal.operation === "create" ? "Addition" : proposal.operation === "update" ? "Correction" : "Removal"}</small><h3>{proposed?.title || current?.title || "Community item"}</h3></div><span>Submitted by {proposal.submittedByName}</span></header>{keys.length > 0 && <div className="diff-table">{keys.map((key) => <div key={key}><strong>{key.replace(/([A-Z])/g, " $1")}</strong><span><small>Current</small>{String((current as unknown as Record<string, unknown>)?.[key] || "-")}</span><span className="proposed"><small>Proposed</small>{String((proposed as unknown as Record<string, unknown>)?.[key] || "-")}</span></div>)}</div>}<p><strong>Reason</strong><br />{proposal.reason || "No reason provided."}</p><label>Admin note <input value={notes[proposal.id] || ""} onChange={(event) => setNotes({ ...notes, [proposal.id]: event.target.value })} /></label><div className="item-actions"><button disabled={proposal.submittedBy === userId} onClick={() => void reviewProposal(project.id, proposal.id, userId, "approved", notes[proposal.id])}>Approve</button><button onClick={() => void reviewProposal(project.id, proposal.id, userId, "rejected", notes[proposal.id])}>Reject</button></div>{proposal.submittedBy === userId && <small>Another admin must approve your own suggestion.</small>}</article>; })}{!proposals.length && <div className="paper-panel empty-manage">No pending suggestions.</div>}</section>;
}

function MembersManager({ project, members, userId }: { project: CloudProject; members: CommunityMember[]; userId: string }) {
  return <section className="members-panel"><header><p className="eyebrow"><span /> Community access</p><h2>Members <small>{members.filter((member) => member.status === "active").length}</small></h2></header><div className="paper-panel member-rows">{members.filter((member) => member.status === "active").map((member) => <div key={member.uid}><span className="member-avatar">{member.displayName?.slice(0, 1).toUpperCase() || "?"}</span><div><strong>{member.displayName || "Community member"}</strong><small>{member.role === "owner" ? "Owner" : member.role === "admin" ? "Admin" : "Member"} · Joined {dateLabel(member.joinedAt) || "recently"}</small></div>{member.role !== "owner" && project.ownerId === userId && <div className="item-actions"><button onClick={() => void updateMemberRole(project, member.uid, member.role === "admin" ? "member" : "admin")}>{member.role === "admin" ? "Make member" : "Make admin"}</button><button onClick={() => { if (window.confirm(`Remove ${member.displayName || "this member"}? They will immediately lose access.`)) void removeMember(project, member.uid); }}>Remove</button></div>}</div>)}</div></section>;
}

function InvitationsManager({ project, invites, userId }: { project: CloudProject; invites: PublicInvite[]; userId: string }) {
  const [label, setLabel] = useState(""); const [expiry, setExpiry] = useState("none"); const [message, setMessage] = useState(""); const [qr, setQr] = useState<Record<string, string>>({});
  async function makeInvite() { const expiresAt = expiry === "none" ? null : new Date(Date.now() + Number(expiry) * 3_600_000).toISOString(); await createInvitation(project, userId, { label, expiresAt }); setLabel(""); setMessage("Invitation created and saved."); }
  async function showQr(invite: PublicInvite) { const url = `${window.location.origin}/join/${invite.token}`; setQr({ ...qr, [invite.token]: await QRCode.toDataURL(url, { width: 260, margin: 2, color: { dark: "#22221f", light: "#fffefa" } }) }); }
  return <section className="invitations-panel"><article className="paper-panel invite-create"><h2>Create invitation</h2><label>Label <small>optional</small><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Residents WhatsApp Group" /></label><label>Expiry<select value={expiry} onChange={(event) => setExpiry(event.target.value)}><option value="none">No expiry</option><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select></label><button className="button button-dark" onClick={() => void makeInvite()}>Create invitation</button>{message && <p role="status">{message}</p>}</article><div className="invite-list">{invites.map((invite) => <article className="paper-panel" key={invite.token}><header><div><strong>{invite.label || invite.code}</strong><small>{invite.status === "active" ? "Active" : "Revoked"}{invite.expiresAt ? ` · expires ${dateLabel(invite.expiresAt)}` : " · no expiry"}</small></div><span className={`status-${invite.status}`}>{invite.status}</span></header>{qr[invite.token] && <Image src={qr[invite.token]} width={220} height={220} unoptimized alt={`QR code for ${project.name}`} />}<div className="item-actions"><button onClick={() => void showQr(invite)}>Show QR</button><button onClick={() => void navigator.clipboard.writeText(`${window.location.origin}/join/${invite.token}`)}>Copy link</button><button onClick={() => void navigator.clipboard.writeText(invite.code)}>Copy code</button>{invite.status === "active" && <button onClick={() => void revokeInvitation(invite.token, invite.code, project.id)}>Revoke</button>}</div></article>)}{!invites.length && <p className="quiet">No invitations yet.</p>}</div></section>;
}

function RemindersManager({ project, reminders }: { project: CloudProject; reminders: Array<{ id: string; [key: string]: unknown }> }) {
  const [message, setMessage] = useState(""); const [nextRunAt, setNextRunAt] = useState(""); const [type, setType] = useState("bin"); const [repeatType, setRepeatType] = useState<"once" | "weekly" | "fortnightly" | "monthly" | "custom">("once"); const [notifyWhen, setNotifyWhen] = useState("evening-before"); const [timezone, setTimezone] = useState(project.timezone || "Europe/London"); const [status, setStatus] = useState("");
  const previewDate = nextRunAt ? new Intl.DateTimeFormat("en-GB", { dateStyle: "full", timeStyle: "short", timeZone: timezone }).format(new Date(nextRunAt)) : "Choose a date and time";
  return <section className="reminder-layout"><form className="paper-panel community-form" onSubmit={async (event) => { event.preventDefault(); await updateCommunitySettings(project.id, { timezone }); await createReminder(project.id, { message, nextRunAt, timezone, reminderType: type, repeatType, notifyWhen, category: type === "bin" ? "bins" : type === "event" ? "events" : "announcements" }); setMessage(""); setNextRunAt(""); setStatus("Reminder scheduled."); }}><h2>Schedule a reminder</h2><label>Reminder type<select value={type} onChange={(event) => setType(event.target.value)}><option value="bin">Bin collection</option><option value="event">Event</option><option value="announcement">Announcement</option><option value="custom">Custom</option></select></label><label>When<select value={repeatType} onChange={(event) => setRepeatType(event.target.value as typeof repeatType)}><option value="once">Once</option><option value="weekly">Weekly</option><option value="fortnightly">Every 2 weeks</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label><label>Notify<select value={notifyWhen} onChange={(event) => setNotifyWhen(event.target.value)}><option value="scheduled">At scheduled time</option><option value="morning-of">Morning of</option><option value="evening-before">Evening before</option><option value="day-before">1 day before</option></select></label><label>Community timezone<select value={timezone} onChange={(event) => setTimezone(event.target.value)}><option>Europe/London</option><option>Europe/Dublin</option><option>America/New_York</option><option>America/Los_Angeles</option><option>Asia/Kolkata</option><option>Australia/Sydney</option></select></label><label>Next date and time<input required type="datetime-local" value={nextRunAt} onChange={(event) => setNextRunAt(event.target.value)} /></label><label>Message<textarea required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Recycling collection is tomorrow." /></label><div className="reminder-preview"><small>Next reminder</small><strong>{previewDate}</strong><span>{timezone}</span><p>&quot;{message || "Your reminder message"}&quot;</p></div><button className="button button-dark">Schedule reminder</button>{status && <p role="status">{status}</p>}</form><article className="paper-panel reminder-history"><h2>Reminder history</h2>{reminders.map((reminder) => <div key={reminder.id}><span><strong>{String(reminder.message || "Reminder")}</strong><small>{String(reminder.status || (reminder.enabled ? "Upcoming" : "Disabled"))}</small></span><i>{String(reminder.repeatType || "once")}</i></div>)}{!reminders.length && <p className="quiet">No reminders scheduled yet.</p>}</article></section>;
}

function WhatsAppPanel({ projectId }: { projectId: string }) {
  const [status, setStatus] = useState<Awaited<ReturnType<typeof getWhatsAppIntegrationStatus>> | null>(null); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [deepLink, setDeepLink] = useState("");
  const refresh = useCallback(() => getWhatsAppIntegrationStatus(projectId).then(setStatus).catch(() => setStatus({ available: false, connected: false, questionOptIn: false, reminderCategories: [] })), [projectId]);
  useEffect(() => { void refresh(); const listener = () => void refresh(); window.addEventListener("focus", listener); return () => window.removeEventListener("focus", listener); }, [refresh]);
  if (!status) return <section className="paper-panel whatsapp-panel" role="status">Checking Community messaging…</section>;
  if (!status.available) return <section className="paper-panel whatsapp-panel"><p className="eyebrow"><span /> Optional messaging</p><h2>WhatsApp is not available for this Community yet.</h2><p>The Community owner needs to finish the secure Meta connection before members can link WhatsApp.</p></section>;
  if (!status.connected) return <section className="paper-panel whatsapp-panel"><p className="eyebrow"><span /> Optional connection</p><h2>{deepLink ? "Complete linking in WhatsApp." : "Connect WhatsApp"}</h2><p>{deepLink ? "This secure one-time link expires shortly. Return here after WhatsApp confirms it." : "Ask Community questions and receive optional reminders through WhatsApp."}</p><label className="check-row"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> Link my WhatsApp identity to this Community</label><button className="button button-dark" disabled={!consent || busy} onClick={async () => { setBusy(true); try { const result = await startWhatsAppLink(projectId, consent); setDeepLink(result.deepLink); setMessage("Your secure link is ready."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create a WhatsApp link."); } finally { setBusy(false); } }}>{busy ? "Preparing…" : "Connect WhatsApp"}</button>{deepLink && <a className="button button-paper" href={deepLink} target="_blank" rel="noreferrer">Open WhatsApp</a>}{message && <p role="status">{message}</p>}</section>;
  const category = (value: string) => status.reminderCategories.includes(value);
  return <section className="paper-panel whatsapp-panel"><p className="eyebrow"><span /> Connected securely</p><h2>WhatsApp connected</h2><p className="masked-phone">{status.maskedPhone}</p><div className="whatsapp-preferences"><label><span>Questions</span><input type="checkbox" checked={status.questionOptIn} onChange={async (event) => { await updateWhatsAppPreferences(projectId, { questionOptIn: event.target.checked, reminderCategories: status.reminderCategories }); await refresh(); }} /></label><fieldset><legend>Reminder categories</legend>{[["bins", "Bin collections"], ["events", "Events"], ["announcements", "Announcements"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={category(value)} onChange={async (event) => { const next = event.target.checked ? [...status.reminderCategories, value] : status.reminderCategories.filter((item) => item !== value); await updateWhatsAppPreferences(projectId, { questionOptIn: status.questionOptIn, reminderCategories: next }); await refresh(); }} />{label}</label>)}</fieldset></div><button className="button button-paper" onClick={async () => { if (!window.confirm("Disconnect WhatsApp from this Community? Other linked Communities are not affected.")) return; await disconnectWhatsApp(projectId); await refresh(); }}>Disconnect WhatsApp</button><small>Reply STOP in WhatsApp to turn off questions and reminders.</small></section>;
}
