"use client";

import QRCode from "qrcode";
import Image from "next/image";
import { FormEvent, useEffect, useMemo, useReducer, useState } from "react";
import { addPublishedItem, addPublishedList, createInvitation, createReminder, deletePublishedItem, deleteReminder, ensureCommunityMemberDirectoryEntry, getCloudProject, removeMember, revokeInvitation, reviewProposal, submitProposal, syncCommunityMemberDirectory, updateMemberRole, updatePublishedItem, watchCommunityItems, watchCommunityLists, watchCommunityMemberDirectory, watchInvitations, watchMembers, watchMembership, watchProposals, watchReminders } from "../../cloud/communityRepository";
import type { CloudProject, CommunityItem, CommunityList, CommunityListType, CommunityMember, CommunityMemberSummary, EditProposal, PublicInvite } from "../../cloud/types";
import { useFirebaseUser } from "../../firebase/FirebaseProvider";
import { PublishedCommunityRecord, queryCommunity } from "../../shared/communityQueryEngine";
import { transferCloudProject } from "../../cloud/accountLifecycle";
import ContactDetailsPanel from "./ContactDetailsPanel";
import DirectoryImportTool from "./DirectoryImportTool";
import { buildContactSearchSuggestions, contactMatchesCategoryFilter, contactSearchReducer, initialContactSearchState, type ContactSearchSuggestion } from "../contactSearchState";

type Tab = "home" | "contacts" | "events" | "manage";
type ItemDraft = Partial<CommunityItem>;
type ContactEntry = { list: CommunityList; item: CommunityItem };
const emptyItem: ItemDraft = { title: "", details: "", category: "", itemType: "directory", phone: "", email: "", website: "", address: "", notes: "", startDate: "", startTime: "", endTime: "", location: "", binType: "", schedule: { type: "fortnightly", firstCollectionDate: "", intervalWeeks: 2 }, enabled: true };
const contactCategories = ["Electrician", "Plumber", "Builder", "Cleaner", "Gardener", "Handyman", "Locksmith", "Tutor", "School", "GP / Health", "Dentist", "Vet", "Council", "Emergency", "Other"];

function Mark() { return <span className="brand-mark" aria-hidden="true"><i /><i /></span>; }
function toDate(value: unknown) { if (!value) return null; const candidate = value as { toDate?: () => Date }; const date = typeof candidate.toDate === "function" ? candidate.toDate() : new Date(String(value)); return Number.isFinite(date.getTime()) ? date : null; }
function dateLabel(value: unknown) { const date = toDate(value); return date ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(date) : ""; }
function reminderTimeLabel(value: unknown, timezone = "Europe/London") { const date = toDate(value); return date ? new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: timezone }).format(date) : ""; }
function normalizeSearch(value: string) { return value.toLowerCase().replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim().split(" ").map((part) => part.length > 4 && part.endsWith("ies") ? `${part.slice(0, -3)}y` : part.length > 3 && part.endsWith("es") ? part.slice(0, -2) : part.length > 3 && part.endsWith("s") ? part.slice(0, -1) : part).join(" "); }
function contactPayload(draft: ItemDraft, itemType: CommunityListType): Omit<CommunityItem, "id"> {
  return { title: String(draft.title || "").trim(), details: String(draft.details || "").trim(), category: String(draft.category || "Other").trim(), itemType, phone: String(draft.phone || "").trim(), email: String(draft.email || "").trim(), website: String(draft.website || "").trim(), address: String(draft.address || "").trim(), notes: String(draft.notes || "").trim(), enabled: true, order: Number(draft.order || Date.now()), schemaVersion: 2 };
}

export default function CommunityClient({ projectId }: { projectId: string }) {
  const { user, loading: authLoading } = useFirebaseUser();
  const [project, setProject] = useState<CloudProject | null>(null);
  const [member, setMember] = useState<CommunityMember | null>(null);
  const [members, setMembers] = useState<CommunityMember[]>([]);
  const [memberDirectory, setMemberDirectory] = useState<CommunityMemberSummary[]>([]);
  const [lists, setLists] = useState<CommunityList[]>([]);
  const [items, setItems] = useState<Record<string, CommunityItem[]>>({});
  const [proposals, setProposals] = useState<EditProposal[]>([]);
  const [invites, setInvites] = useState<PublicInvite[]>([]);
  const [reminders, setReminders] = useState<Array<{ id: string; [key: string]: unknown }>>([]);
  const [reminderToast, setReminderToast] = useState<{ id: string; message: string; reminderType: string; nextRunAt: unknown } | null>(null);
  const [tab, setTab] = useState<Tab>("home");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const canReview = member?.role === "owner" || member?.role === "admin";

  useEffect(() => { if (!user) return; let alive = true; void getCloudProject(projectId).then((next) => { if (alive) setProject(next); }).catch((next) => { if (alive) setError(next instanceof Error ? next.message : "Community unavailable."); }); const unsubscribe = watchMembership(projectId, user.uid, (next) => { if (!alive) return; setMember(next); setLoading(false); }); return () => { alive = false; unsubscribe(); }; }, [projectId, user]);
  useEffect(() => { if (!member || member.status !== "active") return; return watchCommunityLists(projectId, setLists); }, [member, projectId]);
  useEffect(() => { if (!member || member.status !== "active") return; const stops = lists.map((list) => watchCommunityItems(projectId, list.id, (next) => setItems((current) => ({ ...current, [list.id]: next })))); return () => stops.forEach((stop) => stop()); }, [member, projectId, lists]);
  useEffect(() => { if (!user || !member || member.status !== "active") return; void ensureCommunityMemberDirectoryEntry(projectId, member).catch(() => undefined); return watchCommunityMemberDirectory(projectId, setMemberDirectory); }, [member, projectId, user]);
  useEffect(() => { if (!user || !member || member.status !== "active") return; return watchProposals(projectId, user.uid, Boolean(canReview), setProposals); }, [canReview, member, projectId, user]);
  useEffect(() => { if (!member || member.status !== "active") return; return watchReminders(projectId, setReminders); }, [member, projectId]);
  useEffect(() => { if (!canReview) return; const stops = [watchMembers(projectId, setMembers), watchInvitations(projectId, setInvites)]; return () => stops.forEach((stop) => stop()); }, [canReview, projectId]);
  useEffect(() => { if (!canReview || !members.length) return; void syncCommunityMemberDirectory(projectId, members).catch(() => undefined); }, [canReview, members, projectId]);
  useEffect(() => { if (!member || member.status !== "active" || typeof window === "undefined") return; const requested = new URLSearchParams(window.location.search).get("tab"); const allowed: Tab[] = ["home", "contacts", "events", ...(canReview ? ["manage" as const] : [])]; const timer = window.setTimeout(() => { if (requested && allowed.includes(requested as Tab)) setTab(requested as Tab); else setTab((current) => current === "manage" && !canReview ? "home" : current); }, 0); return () => window.clearTimeout(timer); }, [canReview, member]);
  useEffect(() => {
    if (!member || member.status !== "active" || typeof window === "undefined") return;
    function checkDueReminders() {
      const now = Date.now();
      const due = reminders
        .map((reminder) => ({ reminder, date: toDate(reminder.nextRunAt) }))
        .filter(({ reminder, date }) => Boolean(date) && date!.getTime() <= now && date!.getTime() >= now - 60 * 60 * 1000 && reminder.enabled !== false && String(reminder.status || "upcoming") !== "disabled")
        .sort((a, b) => b.date!.getTime() - a.date!.getTime())
        .find(({ reminder, date }) => !window.localStorage.getItem(`circa_reminder_seen:${projectId}:${reminder.id}:${date!.getTime()}`));
      if (!due) return;
      const storageKey = `circa_reminder_seen:${projectId}:${due.reminder.id}:${due.date!.getTime()}`;
      window.localStorage.setItem(storageKey, "1");
      setReminderToast({ id: due.reminder.id, message: String(due.reminder.message || "Community reminder"), reminderType: String(due.reminder.reminderType || "reminder"), nextRunAt: due.reminder.nextRunAt });
    }
    const initialTimer = window.setTimeout(checkDueReminders, 0);
    const timer = window.setInterval(checkDueReminders, 15_000);
    return () => { window.clearTimeout(initialTimer); window.clearInterval(timer); };
  }, [member, projectId, reminders]);

  function selectTab(next: Tab) {
    if (next === "manage" && !canReview) return;
    setTab(next);
    if (typeof window !== "undefined") { const url = new URL(window.location.href); if (next === "home") url.searchParams.delete("tab"); else url.searchParams.set("tab", next); window.history.replaceState(null, "", `${url.pathname}${url.search}`); }
  }

  const records = useMemo(() => lists.flatMap((list) => (items[list.id] || []).map((item): PublishedCommunityRecord => ({ listId: list.id, listTitle: list.title, itemId: item.id, title: item.title, details: item.details, category: item.category, itemType: item.itemType || list.listType, phone: item.phone, email: item.email, url: item.url || item.website, website: item.website, address: item.address, notes: item.notes, date: item.date, startDate: item.startDate, startTime: item.startTime, endTime: item.endTime, location: item.location, binType: item.binType, schedule: item.schedule, timezone: project?.timezone, enabled: item.enabled }))), [items, lists, project?.timezone]);

  if (authLoading || (Boolean(user) && loading)) return <main className="cloud-page centred-state" role="status">Opening this Community…</main>;
  if (!user || user.isAnonymous) return <main className="cloud-page centred-state"><h1>Sign in to return to this Community.</h1><p>Your Community membership is tied to your Circa account.</p><a className="button button-dark" href={`/auth?returnTo=/community/${projectId}`}>Sign in</a></main>;
  if (!member || member.status !== "active") return <main className="cloud-page centred-state"><h1>This Community is private.</h1><p>Use an active invitation link or code to join.</p><a className="button button-paper" href="/join">Enter a Community code</a></main>;
  if (!project) return <main className="cloud-page centred-state"><h1>Community unavailable.</h1><p>{error || "Circa could not open this Community."}</p></main>;

  const tabs: Array<[Tab, string]> = [["home", "Home"], ["contacts", "Contacts"], ["events", "Events"], ...(canReview ? [["manage", proposals.length ? `Manage (${proposals.length})` : "Manage"] as [Tab, string]] : [])];
  return <main className={`cloud-page community-page${canReview ? " is-admin" : ""}`}><header className="community-header"><a className="brand" href="/"><Mark /><span className="brand-name">Circa<sup>beta</sup></span></a><div><span className="saved-dot" /> Community data live</div><a href="/account">Your Circa</a></header><section className="community-title"><div><p className="eyebrow"><span /> Circa Community</p><h1>{project.name}</h1><p>{project.location}{project.location && project.description ? " - " : ""}{project.description}</p></div>{canReview && <button className="role-link" onClick={() => selectTab("manage")}>Community {member.role}</button>}</section><nav className="community-tabs" aria-label="Community sections">{tabs.map(([value, label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => selectTab(value)}>{label}</button>)}</nav>
    {tab === "home" && <CommunityHome project={project} lists={lists} items={items} records={records} reminders={reminders} canReview={Boolean(canReview)} onTab={selectTab} />}
    {tab === "contacts" && <ContactsView lists={lists.filter((list) => list.listType !== "event" && list.listType !== "bin")} items={items} user={user} projectId={projectId} canReview={Boolean(canReview)} members={memberDirectory.length ? memberDirectory : canReview ? members.map((item) => ({ uid: item.uid, role: item.role, status: item.status, displayName: item.displayName || (item.role === "owner" ? "Community owner" : item.role === "admin" ? "Community admin" : "Community member"), joinedAt: item.joinedAt })) : []} />}
    {tab === "events" && <EventsView lists={lists} items={items} user={user} projectId={projectId} canReview={Boolean(canReview)} />}
    {tab === "manage" && canReview && <ManageView project={project} lists={lists} proposals={proposals} members={members} invites={invites} reminders={reminders} userId={user.uid} />}
    {reminderToast && <ReminderToast reminder={reminderToast} timezone={project.timezone || "Europe/London"} onClose={() => setReminderToast(null)} />}
  </main>;
}

function ReminderToast({ reminder, timezone, onClose }: { reminder: { message: string; reminderType: string; nextRunAt: unknown }; timezone: string; onClose: () => void }) {
  return <aside className="reminder-toast" role="status" aria-live="polite"><button onClick={onClose} aria-label="Dismiss reminder">×</button><span className="reminder-toast-kicker">Reminder</span><strong>{reminder.message}</strong><small>{reminder.reminderType.replace(/-/g, " ")} · {reminderTimeLabel(reminder.nextRunAt, timezone)}</small></aside>;
}

function CommunityHome({ project, lists, items, records, reminders, canReview, onTab }: { project: CloudProject; lists: CommunityList[]; items: Record<string, CommunityItem[]>; records: PublishedCommunityRecord[]; reminders: Array<{ id: string; [key: string]: unknown }>; canReview: boolean; onTab: (tab: Tab) => void }) {
  const [now, setNow] = useState<Date | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => setNow(new Date()), 0); return () => window.clearTimeout(timer); }, []);
  // Home collection status must only inspect actual collection records.
  // Directory contacts such as "Bin cleaning" are services, not bin schedules.
  const collectionRecords = records.filter((record) => record.itemType === "bin" || Boolean(record.schedule));
  const tomorrow = queryCommunity("What bin is tomorrow?", collectionRecords, { timezone: project.timezone });
  const nextEvent = queryCommunity("What is the next event?", records, { timezone: project.timezone });
  const dateText = now ? new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", timeZone: project.timezone || "Europe/London" }).format(now) : "Community overview";
  const hour = now?.getHours();
  const greeting = hour == null ? "Welcome" : hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
  const liveReminders = reminders.map((reminder) => ({ reminder, date: toDate(reminder.nextRunAt) })).filter(({ reminder, date }) => Boolean(date) && reminder.enabled !== false && String(reminder.status || "upcoming") !== "disabled").sort((a, b) => a.date!.getTime() - b.date!.getTime());
  const nextReminder = liveReminders.find(({ date }) => !now || date!.getTime() >= now.getTime() - 60_000) || liveReminders[0];
  const contactCount = lists.filter((list) => !["event", "bin"].includes(list.listType)).reduce((total, list) => total + (items[list.id] || []).filter((item) => item.enabled !== false).length, 0);
  const eventCount = lists.filter((list) => list.listType === "event").reduce((total, list) => total + (items[list.id] || []).filter((item) => item.enabled !== false).length, 0);
  const visibleLists = lists.filter((list) => list.listType !== "bin");
  function openReminders() { if (typeof window !== "undefined") { const url = new URL(window.location.href); url.searchParams.set("tab", "manage"); url.searchParams.set("manage", "reminders"); window.history.replaceState(null, "", `${url.pathname}${url.search}`); } onTab("manage"); }
  return <section className="community-home community-home-v2">
    <header className="community-home-intro"><div><p>{dateText}</p><h2>{greeting}.</h2><span>Here&apos;s what&apos;s happening in {project.name}.</span></div><div className="home-quick-actions"><button onClick={() => onTab("contacts")}>Find a contact</button><button onClick={() => onTab("events")}>View events</button>{canReview && <button className="primary" onClick={() => onTab("manage")}>Manage Community</button>}</div></header>
    <section className="community-snapshot" aria-label="Community overview"><button onClick={() => onTab("contacts")}><strong>{contactCount}</strong><span>contacts</span><small>Search useful people and services</small></button><button onClick={() => onTab("events")}><strong>{eventCount}</strong><span>events</span><small>See what&apos;s coming up</small></button><div><strong>{liveReminders.length}</strong><span>reminders</span><small>Scheduled for this Community</small></div></section>
    <div className="home-status-grid">
      <article className="paper-panel home-status-card reminder-status"><div className="home-status-top"><span className="home-status-icon">◷</span><small>Next reminder</small></div>{nextReminder ? <><h3>{String(nextReminder.reminder.message || "Community reminder")}</h3><p>{reminderTimeLabel(nextReminder.reminder.nextRunAt, project.timezone || "Europe/London")}</p><span className="home-status-meta">{String(nextReminder.reminder.repeatType || "once").replace(/-/g, " ")}</span></> : <><h3>No reminders yet</h3><p>{canReview ? "Schedule one from Manage when the Community needs a nudge." : "An admin has not scheduled a Community reminder yet."}</p></>}{canReview && <button className="home-card-link" onClick={openReminders}>Open reminders →</button>}</article>
      <article className="paper-panel home-status-card collection-status"><div className="home-status-top"><span className="home-status-icon">↻</span><small>Tomorrow&apos;s collection</small></div><h3>{tomorrow.itemIds.length ? tomorrow.answer.split(" is collected")[0] : "No collection found"}</h3><p>{tomorrow.answer}</p></article>
      <article className="paper-panel home-status-card event-status"><div className="home-status-top"><span className="home-status-icon">◇</span><small>Next event</small></div><h3>{nextEvent.itemIds.length ? nextEvent.answer.split(" is ")[0] : "Nothing published yet"}</h3><p>{nextEvent.answer}</p><button className="home-card-link" onClick={() => onTab("events")}>See events →</button></article>
    </div>
    <section className="community-explore community-explore-v2"><header><div><p className="eyebrow"><span /> Browse the Community</p><h2>Explore</h2></div><button onClick={() => onTab("contacts")}>View all contacts →</button></header><div>{visibleLists.map((list) => <button key={list.id} onClick={() => onTab(list.listType === "event" ? "events" : "contacts")}><span>{list.title}</span><strong>{(items[list.id] || []).length}</strong><small>{list.listType === "event" ? "Events" : list.listType === "school" ? "Schools" : "Contacts"}</small><i>→</i></button>)}</div></section>
  </section>;
}

function ContactsView({ lists, items, user, projectId, canReview, members }: { lists: CommunityList[]; items: Record<string, CommunityItem[]>; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; projectId: string; canReview: boolean; members: CommunityMemberSummary[] }) {
  const [search, dispatchSearch] = useReducer(contactSearchReducer, initialContactSearchState);
  const query = search.query;
  const [selected, setSelected] = useState<ContactEntry | null>(null);
  const [showMembers, setShowMembers] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<ItemDraft>({ ...emptyItem, category: "Electrician" });
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const entries = useMemo(() => lists.flatMap((list) => (items[list.id] || []).filter((item) => item.enabled !== false).map((item) => ({ list, item }))), [items, lists]);
  const results = useMemo(() => {
    const matching = entries.filter(({ list, item }) => contactMatchesCategoryFilter(item.category || list.title, query, search.selectedCategory, normalizeSearch));
    return search.selectedCategory ? matching : matching.sort((a, b) => a.item.title.localeCompare(b.item.title));
  }, [entries, query, search.selectedCategory]);
  const suggestions = useMemo(() => buildContactSearchSuggestions(entries.map(({ list, item }) => ({ category: item.category || list.title })), query, normalizeSearch), [entries, query]);
  const activeMembers = members.filter((item) => item.status === "active");
  const targetList = lists.find((list) => list.listType === "contact") || lists.find((list) => list.listType === "directory") || lists.find((list) => list.listType === "school") || lists[0];

  function resetDraft() { setDraft({ ...emptyItem, category: "Electrician", itemType: targetList?.listType || "contact" }); }
  async function addContact(event: FormEvent) {
    event.preventDefault(); if (!targetList || !draft.title?.trim()) return; setBusy(true); setMessage("");
    try { const payload = contactPayload(draft, targetList.listType); if (canReview) { await addPublishedItem(projectId, targetList.id, payload); setMessage("Contact added."); } else { await submitProposal(user, projectId, { listId: targetList.id, itemId: "", operation: "create", proposedItem: payload, reason: "New contact" }); setMessage("Contact sent to the Community admin for review."); } setShowAdd(false); resetDraft(); }
    catch (next) { setMessage(next instanceof Error ? next.message : "Circa could not add that contact."); }
    finally { setBusy(false); }
  }
  async function saveContact() {
    if (!canReview || !selected || !draft.title?.trim()) return; setBusy(true); setMessage("");
    try { const payload = contactPayload({ ...selected.item, ...draft }, selected.list.listType); await updatePublishedItem(projectId, selected.list.id, selected.item.id, payload); setMessage("Contact updated."); setEditing(false); setSelected(null); }
    catch (next) { setMessage(next instanceof Error ? next.message : "Circa could not update that contact."); }
    finally { setBusy(false); }
  }
  function chooseSearchSuggestion(suggestion: ContactSearchSuggestion) {
    dispatchSearch({ type: "choose-category", label: suggestion.label });
  }

  return <section className="contacts-view"><header className="contacts-heading"><div><p className="eyebrow"><span /> Community contacts</p><h2>Contacts</h2><p>Find trusted services, people and useful local information.</p></div><div className="contacts-actions"><button className="member-count-button" onClick={() => setShowMembers(true)}>{activeMembers.length} {activeMembers.length === 1 ? "member" : "members"}</button><button className="button button-dark button-small" onClick={() => { resetDraft(); setShowAdd(true); }}>＋ Add contact</button></div></header>
    <div className="contact-search-shell" onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) dispatchSearch({ type: "close" }); }}><label className="contact-search"><span>⌕</span><input role="combobox" aria-autocomplete="list" value={query} onChange={(event) => dispatchSearch({ type: "change", query: event.target.value })} onFocus={() => dispatchSearch({ type: "focus" })} onKeyDown={(event) => { if (event.key === "Escape") dispatchSearch({ type: "close" }); }} placeholder="Filter contacts by category…" aria-label="Filter contacts by category" aria-expanded={search.suggestionsOpen && suggestions.length > 0} aria-controls="contact-search-suggestions" /></label>{search.suggestionsOpen && suggestions.length > 0 && <div id="contact-search-suggestions" className="contact-suggestions" role="listbox" aria-label="Category suggestions">{suggestions.map((suggestion) => <button type="button" role="option" aria-selected="false" key={suggestion.label} onPointerDown={(event) => event.preventDefault()} onPointerUp={() => chooseSearchSuggestion(suggestion)} onClick={() => chooseSearchSuggestion(suggestion)}>{suggestion.label}</button>)}</div>}</div>
    <div className="contact-table" role="table" aria-label="Community contacts"><div className="contact-table-head" role="row"><span>Name</span><span>Category</span><span>Phone</span><span>Email</span></div>{results.map((entry) => <button className="contact-row" role="row" aria-label={`Open ${entry.item.title} details`} key={`${entry.list.id}-${entry.item.id}`} onClick={() => { dispatchSearch({ type: "close" }); setSelected(entry); setEditing(false); setDraft(entry.item); }}><strong data-label="Name">{entry.item.title}</strong><span data-label="Category">{entry.item.category || entry.list.title}</span><span data-label="Phone" className={!entry.item.phone ? "contact-value-empty" : ""}>{entry.item.phone || "Not provided"}</span><span data-label="Email" className={!entry.item.email ? "contact-value-empty" : ""}>{entry.item.email || "Not provided"}</span></button>)}{!results.length && <div className="contact-empty">No contacts match “{query}”.</div>}</div>
    {message && <div className="contacts-message" role="status">{message}</div>}

    {showAdd && <div className="popover-backdrop" onMouseDown={() => setShowAdd(false)}><form className="add-popover contact-editor" onSubmit={addContact} onMouseDown={(event) => event.stopPropagation()}><button type="button" className="popover-close" onClick={() => setShowAdd(false)} aria-label="Close add contact">×</button><span className="form-kicker">Quick add</span><h2>Add a contact</h2><p>Just the useful details. You can add more later if needed.</p><label>Name<input required autoFocus maxLength={120} value={draft.title || ""} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="e.g. Northside Electrical" /></label><label>Category<input required list="contact-category-options" value={draft.category || ""} onChange={(event) => setDraft({ ...draft, category: event.target.value })} placeholder="e.g. Electrician" /></label><datalist id="contact-category-options">{contactCategories.map((category) => <option key={category} value={category} />)}</datalist><div className="contact-editor-pair"><label>Phone<input value={draft.phone || ""} onChange={(event) => setDraft({ ...draft, phone: event.target.value })} /></label><label>Email<input type="email" value={draft.email || ""} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /></label></div>{!targetList && <p role="alert">An admin needs to create a Contacts or Directory section before contacts can be added.</p>}<button className="button button-dark" disabled={busy || !targetList}>{busy ? "Saving…" : canReview ? "Add contact" : "Send for review"}</button></form></div>}

    {selected && <div className="popover-backdrop" onMouseDown={() => setSelected(null)}><div className="add-popover contact-detail-popover" role="dialog" aria-modal="true" aria-labelledby="contact-detail-title" onMouseDown={(event) => event.stopPropagation()}><button className="popover-close" onClick={() => setSelected(null)} aria-label="Close contact details">×</button><span className="form-kicker">{selected.item.category || selected.list.title}</span><h2 id="contact-detail-title">{selected.item.title}</h2>{editing && canReview ? <><label>Name<input value={draft.title || ""} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>Category<input list="contact-category-options" value={draft.category || ""} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></label><div className="contact-editor-pair"><label>Phone<input value={draft.phone || ""} onChange={(event) => setDraft({ ...draft, phone: event.target.value })} /></label><label>Email<input type="email" value={draft.email || ""} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /></label></div><div className="contact-detail-actions"><button className="button button-dark" disabled={busy} onClick={() => void saveContact()}>{busy ? "Saving…" : "Save changes"}</button><button className="button button-paper" onClick={() => { setEditing(false); setDraft(selected.item); }}>Cancel</button></div></> : <><ContactDetailsPanel item={selected.item} list={selected.list} /><div className="contact-detail-actions">{canReview && <button className="button button-paper" onClick={() => { setDraft(selected.item); setEditing(true); }}>Edit contact</button>}{canReview && <button className="danger-text" onClick={async () => { if (window.confirm(`Delete ${selected.item.title}?`)) { await deletePublishedItem(projectId, selected.list.id, selected.item.id); setSelected(null); setMessage("Contact deleted."); } }}>Delete</button>}{!canReview && selected.item.createdBy === user.uid && <button className="danger-text" onClick={async () => { if (window.confirm(`Ask an admin to remove ${selected.item.title}?`)) { await submitProposal(user, projectId, { listId: selected.list.id, itemId: selected.item.id, operation: "delete", proposedItem: null, reason: "Contributor requested removal" }); setSelected(null); setMessage("Removal request sent to an admin for review."); } }}>Request removal</button>}{!canReview && selected.item.createdBy !== user.uid && <small className="member-readonly-note">Members can view Community contacts and propose additions or corrections for admin review.</small>}</div></>}</div></div>}
    {showMembers && <div className="popover-backdrop" onMouseDown={() => setShowMembers(false)}><div className="add-popover member-directory-popover" role="dialog" aria-modal="true" aria-labelledby="community-members-title" onMouseDown={(event) => event.stopPropagation()}><button className="popover-close" onClick={() => setShowMembers(false)} aria-label="Close member list">×</button><span className="form-kicker">Community</span><h2 id="community-members-title">{activeMembers.length} {activeMembers.length === 1 ? "member" : "members"}</h2><div className="member-directory-list">{activeMembers.map((person) => <div key={person.uid}><span className="member-avatar">{person.displayName?.slice(0, 1).toUpperCase() || "?"}</span><div><strong>{person.displayName || "Community member"}</strong><small>{person.role === "owner" ? "Owner" : person.role === "admin" ? "Admin" : "Member"}{person.joinedAt ? ` · Joined ${dateLabel(person.joinedAt)}` : ""}</small></div></div>)}</div></div></div>}
  </section>;
}

function EventsView({ lists, items, user, projectId, canReview }: { lists: CommunityList[]; items: Record<string, CommunityItem[]>; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; projectId: string; canReview: boolean }) {
  const eventLists = lists.filter((list) => list.listType === "event" || (items[list.id] || []).some((item) => item.itemType === "event"));
  return <section className="events-board"><header><p className="eyebrow"><span /> What&apos;s coming up</p><h2>Community events.</h2></header>{eventLists.flatMap((list) => (items[list.id] || []).map((item) => <CommunityItemCard key={item.id} item={item} listId={list.id} projectId={projectId} user={user} canReview={canReview} />)).sort((a, b) => String(a.props.item.startDate || "").localeCompare(String(b.props.item.startDate || "")))}</section>;
}

function CommunityItemCard({ item, listId, projectId, user, canReview }: { item: CommunityItem; listId: string; projectId: string; user: NonNullable<ReturnType<typeof useFirebaseUser>["user"]>; canReview: boolean }) {
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<ItemDraft>(item); const [message, setMessage] = useState("");
  const fields = [["Phone", item.phone], ["Email", item.email], ["Website", item.website || item.url], ["Address", item.address], ["Opening", item.openingInformation], ["Date", item.startDate || item.date], ["Time", [item.startTime, item.endTime].filter(Boolean).join(" - ")], ["Location", item.location], ["Notes", item.notes]].filter(([, value]) => Boolean(value));
  const canDeleteOwn = !canReview && item.createdBy === user.uid;
  return <div className="community-item"><h3>{item.title}</h3>{item.details && <p>{item.details}</p>}<dl>{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{label === "Website" ? <a href={String(value)} target="_blank" rel="noreferrer">Open website</a> : label === "Email" ? <a href={`mailto:${value}`}>{value}</a> : label === "Phone" ? <a href={`tel:${value}`}>{value}</a> : value}</dd></div>)}</dl>{editing && canReview && <ItemFields item={draft} onChange={setDraft} compact />}{editing && canReview ? <div className="item-actions"><button onClick={async () => { await updatePublishedItem(projectId, listId, item.id, draft); setMessage("Updated."); setEditing(false); }}>Save changes</button><button onClick={() => setEditing(false)}>Cancel</button></div> : <div className="item-actions">{canReview && <button onClick={() => setEditing(true)}>Edit</button>}{canReview && <button onClick={async () => { if (window.confirm(`Delete ${item.title}? This cannot be undone.`)) await deletePublishedItem(projectId, listId, item.id); }}>Delete</button>}{canDeleteOwn && <button className="danger-text" onClick={async () => { if (window.confirm(`Ask an admin to remove ${item.title}?`)) { await submitProposal(user, projectId, { listId, itemId: item.id, operation: "delete", proposedItem: null, reason: "Contributor requested removal" }); setMessage("Removal request sent for admin review."); } }}>Request removal</button>}</div>}{message && <small role="status">{message}</small>}</div>;
}

function ItemFields({ item, onChange, compact = false }: { item: ItemDraft; onChange: (item: ItemDraft) => void; compact?: boolean }) {
  const set = (key: keyof CommunityItem, value: unknown) => onChange({ ...item, [key]: value });
  const contactLike = !item.itemType || ["directory", "contact", "school", "custom"].includes(item.itemType);
  return <div className={compact ? "item-fields compact" : "item-fields"}><label>Name / title<input required value={item.title || ""} onChange={(event) => set("title", event.target.value)} /></label>{contactLike && <><label>Category<input list="admin-contact-categories" value={item.category || ""} onChange={(event) => set("category", event.target.value)} placeholder="Electrician, school, council…" /></label><datalist id="admin-contact-categories">{contactCategories.map((category) => <option key={category} value={category} />)}</datalist><div className="field-pair"><label>Phone<input value={item.phone || ""} onChange={(event) => set("phone", event.target.value)} /></label><label>Email<input type="email" value={item.email || ""} onChange={(event) => set("email", event.target.value)} /></label></div></>}{item.itemType === "event" && <><div className="field-pair"><label>Date<input type="date" value={item.startDate || ""} onChange={(event) => set("startDate", event.target.value)} /></label><label>Start time<input type="time" value={item.startTime || ""} onChange={(event) => set("startTime", event.target.value)} /></label></div><div className="field-pair"><label>End time<input type="time" value={item.endTime || ""} onChange={(event) => set("endTime", event.target.value)} /></label><label>Location<input value={item.location || ""} onChange={(event) => set("location", event.target.value)} /></label></div></>}{item.itemType === "bin" && <><label>Bin type<input value={item.binType || ""} onChange={(event) => set("binType", event.target.value)} placeholder="Recycling, general waste…" /></label><div className="field-pair"><label>Schedule<select value={item.schedule?.type || "fortnightly"} onChange={(event) => set("schedule", { ...(item.schedule || { firstCollectionDate: "" }), type: event.target.value })}><option value="once">Once</option><option value="weekly">Weekly</option><option value="fortnightly">Every 2 weeks</option><option value="custom">Custom</option></select></label><label>First collection<input type="date" value={item.schedule?.firstCollectionDate || ""} onChange={(event) => set("schedule", { ...(item.schedule || { type: "fortnightly" }), firstCollectionDate: event.target.value })} /></label></div></>}</div>;
}

function ManageView({ project, lists, proposals, members, invites, reminders, userId }: { project: CloudProject; lists: CommunityList[]; proposals: EditProposal[]; members: CommunityMember[]; invites: PublicInvite[]; reminders: Array<{ id: string; [key: string]: unknown }>; userId: string }) {
  type ManageSection = "content" | "review" | "members" | "invites" | "reminders";
  const [section, setSection] = useState<ManageSection>("content");
  useEffect(() => { if (typeof window === "undefined") return; const requested = new URLSearchParams(window.location.search).get("manage") as ManageSection | null; if (!requested || !["content", "review", "members", "invites", "reminders"].includes(requested)) return; const timer = window.setTimeout(() => setSection(requested), 0); return () => window.clearTimeout(timer); }, []);
  function chooseSection(value: ManageSection) { setSection(value); if (typeof window !== "undefined") { const url = new URL(window.location.href); url.searchParams.set("manage", value); window.history.replaceState(null, "", `${url.pathname}${url.search}`); } }
  return <section className="manage-shell" id="community-manage"><nav className="manage-nav">{(["content", "review", "members", "invites", "reminders"] as const).map((value) => <button className={section === value ? "active" : ""} onClick={() => chooseSection(value)} key={value}>{value === "review" ? `Review (${proposals.length})` : value[0].toUpperCase() + value.slice(1)}</button>)}</nav>{section === "content" && <ContentManager project={project} lists={lists} />}{section === "review" && <ReviewQueue project={project} proposals={proposals} userId={userId} />}{section === "members" && <MembersManager project={project} members={members} userId={userId} />}{section === "invites" && <InvitationsManager project={project} invites={invites} userId={userId} />}{section === "reminders" && <RemindersManager project={project} reminders={reminders} />}</section>;
}

function ContentManager({ project, lists }: { project: CloudProject; lists: CommunityList[] }) {
  const [sectionTitle, setSectionTitle] = useState(""); const [sectionType, setSectionType] = useState<CommunityListType>("directory"); const [showSectionForm, setShowSectionForm] = useState(false); const [listId, setListId] = useState(""); const [draft, setDraft] = useState<ItemDraft>(emptyItem); const [message, setMessage] = useState("");
  const target = listId || lists[0]?.id || ""; const selectedList = lists.find((list) => list.id === target); const type = selectedList?.listType || "custom"; const effectiveDraft = { ...draft, itemType: type };
  async function addSection(event: FormEvent) { event.preventDefault(); if (!sectionTitle.trim()) return; const id = await addPublishedList(project.id, sectionTitle, sectionType); setSectionTitle(""); setShowSectionForm(false); setListId(id); setDraft({ ...emptyItem, itemType: sectionType }); setMessage("Section added."); }
  async function publish(event: FormEvent) { event.preventDefault(); if (!target || !effectiveDraft.title?.trim()) return; await addPublishedItem(project.id, target, effectiveDraft); setDraft({ ...emptyItem, itemType: type }); setMessage("Published immediately."); }
  return <section className="admin-content-v2"><header className="manage-page-heading"><div><p className="eyebrow"><span /> Published information</p><h2>Content</h2><p>Choose a section, add the essentials, and publish. No long forms.</p></div><button className="button button-paper button-small" onClick={() => setShowSectionForm((value) => !value)}>{showSectionForm ? "Close" : "+ New section"}</button></header><div className="admin-content-workspace"><aside className="paper-panel admin-section-panel"><div className="admin-panel-title"><strong>Sections</strong><span>{lists.length}</span></div>{showSectionForm && <form className="compact-section-form" onSubmit={addSection}><label>Section name<input autoFocus required value={sectionTitle} onChange={(event) => setSectionTitle(event.target.value)} placeholder="e.g. Local services" /></label><label>Type<select value={sectionType} onChange={(event) => setSectionType(event.target.value as CommunityListType)}><option value="directory">Contacts / services</option><option value="contact">Contact</option><option value="event">Event</option><option value="bin">Bin collection</option><option value="school">School</option><option value="custom">Custom</option></select></label><button className="button button-dark button-small">Add section</button></form>}<div className="admin-section-list">{lists.map((list) => <button key={list.id} className={target === list.id ? "active" : ""} onClick={() => { setListId(list.id); setDraft({ ...emptyItem, itemType: list.listType }); setMessage(""); }}><span>{list.title}</span><small>{list.listType === "directory" ? "Contacts" : list.listType}</small><i>→</i></button>)}{!lists.length && <p className="quiet">Create the first section to start publishing.</p>}</div></aside><article className="paper-panel admin-quick-publish"><div className="admin-panel-title"><div><small>Quick publish</small><strong>{selectedList?.title || "Choose a section"}</strong></div>{selectedList && <span>{selectedList.listType}</span>}</div>{selectedList ? <form className="quick-publish-form" onSubmit={publish}><ItemFields item={effectiveDraft} onChange={setDraft} /><div className="quick-publish-actions"><button className="button button-dark" disabled={!effectiveDraft.title?.trim()}>Publish now</button><small>Admin changes appear immediately.</small></div></form> : <div className="admin-empty-state">Choose or create a section first.</div>}{message && <p className="admin-success" role="status">{message}</p>}</article></div>{selectedList && <DirectoryImportTool projectId={project.id} listId={selectedList.id} listTitle={selectedList.title} />}</section>;
}

function ReviewQueue({ project, proposals, userId }: { project: CloudProject; proposals: EditProposal[]; userId: string }) {
  const [working, setWorking] = useState("");
  const visibleKeys = (proposal: EditProposal) => { const current = proposal.currentItem || null; const proposed = proposal.proposedItem || null; return [...new Set([...Object.keys(current || {}), ...Object.keys(proposed || {})])].filter((key) => !["id", "schemaVersion", "order", "details", "description", "website", "url", "address", "notes", "createdBy", "createdByName"].includes(key) && JSON.stringify((current as unknown as Record<string, unknown>)?.[key]) !== JSON.stringify((proposed as unknown as Record<string, unknown>)?.[key])); };
  async function decide(proposal: EditProposal, decision: "approved" | "rejected") { setWorking(proposal.id); try { await reviewProposal(project.id, proposal.id, userId, decision); } finally { setWorking(""); } }
  return <section className="review-list review-list-v2"><header className="manage-page-heading"><div><p className="eyebrow"><span /> Review queue</p><h2>Review</h2><p>Approve useful member additions or reject them in one click.</p></div><span className="review-count">{proposals.length} pending</span></header><div className="review-card-list">{proposals.map((proposal) => { const current = proposal.currentItem || null; const proposed = proposal.proposedItem || null; const keys = visibleKeys(proposal); return <article className="paper-panel proposal-diff proposal-card-v2" key={proposal.id}><header><div><small>{proposal.operation === "create" ? "New information" : proposal.operation === "update" ? "Change request" : "Removal request"}</small><h3>{proposed?.title || current?.title || "Community item"}</h3><span>From {proposal.submittedByName}</span></div><span className="proposal-operation">{proposal.operation}</span></header>{keys.length > 0 && <div className="review-change-list">{keys.map((key) => <div key={key}><strong>{key.replace(/([A-Z])/g, " $1")}</strong><span>{String((proposed as unknown as Record<string, unknown>)?.[key] || (current as unknown as Record<string, unknown>)?.[key] || "-")}</span></div>)}</div>}<div className="review-actions"><button className="button button-dark button-small" disabled={proposal.submittedBy === userId || working === proposal.id} onClick={() => void decide(proposal, "approved")}>{working === proposal.id ? "Working…" : "Approve"}</button><button className="button button-paper button-small" disabled={proposal.submittedBy === userId || working === proposal.id} onClick={() => void decide(proposal, "rejected")}>Reject</button>{proposal.submittedBy === userId && <small>Another admin must review your own suggestion.</small>}</div></article>; })}{!proposals.length && <div className="paper-panel empty-manage"><strong>All clear.</strong><p>There are no member suggestions waiting for review.</p></div>}</div></section>;
}

function MembersManager({ project, members, userId }: { project: CloudProject; members: CommunityMember[]; userId: string }) {
  const [query, setQuery] = useState("");
  const [ownershipBusy, setOwnershipBusy] = useState("");
  const [ownershipError, setOwnershipError] = useState("");
  const active = members.filter((member) => member.status === "active");
  const visible = active.filter((member) => !query.trim() || `${member.displayName} ${member.role}`.toLowerCase().includes(query.trim().toLowerCase()));
  const admins = active.filter((member) => member.role === "owner" || member.role === "admin").length;
  async function transfer(member: CommunityMember) { if (!window.confirm(`Transfer permanent ownership of ${project.name} to ${member.displayName || "this member"}? You will become an admin.`)) return; setOwnershipBusy(member.uid); setOwnershipError(""); try { await transferCloudProject(project.id, member.uid); window.location.reload(); } catch (error) { setOwnershipError(error instanceof Error ? error.message : "Circa could not transfer ownership."); setOwnershipBusy(""); } }
  return <section className="members-panel members-panel-v2"><header className="manage-page-heading"><div><p className="eyebrow"><span /> Community access</p><h2>Members</h2><p>See who belongs here and manage roles without opening individual profiles.</p></div><div className="member-stats"><span><strong>{active.length}</strong> active</span><span><strong>{admins}</strong> admins</span></div></header>{ownershipError && <p className="cloud-warning" role="alert">{ownershipError}</p>}<label className="member-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search members" /></label><div className="paper-panel member-rows member-rows-v2">{visible.map((member) => <div key={member.uid}><span className="member-avatar">{member.displayName?.slice(0, 1).toUpperCase() || "?"}</span><div><strong>{member.displayName || "Community member"}</strong><small>Joined {dateLabel(member.joinedAt) || "recently"}</small></div><span className={`member-role role-${member.role}`}>{member.role === "owner" ? "Owner" : member.role === "admin" ? "Admin" : "Member"}</span>{member.role !== "owner" && project.ownerId === userId && <div className="item-actions member-row-actions"><button disabled={Boolean(ownershipBusy)} onClick={() => void transfer(member)}>{ownershipBusy === member.uid ? "Transferring…" : "Transfer ownership"}</button><button onClick={() => void updateMemberRole(project, member.uid, member.role === "admin" ? "member" : "admin")}>{member.role === "admin" ? "Make member" : "Make admin"}</button><button className="danger-text" onClick={() => { if (window.confirm(`Remove ${member.displayName || "this member"}? They will immediately lose access.`)) void removeMember(project, member.uid); }}>Remove</button></div>}</div>)}{!visible.length && <div className="member-no-results">No members match “{query}”.</div>}</div></section>;
}

function InvitationsManager({ project, invites, userId }: { project: CloudProject; invites: PublicInvite[]; userId: string }) {
  const [label, setLabel] = useState(""); const [expiry, setExpiry] = useState("none"); const [message, setMessage] = useState(""); const [qr, setQr] = useState<Record<string, string>>({});
  async function makeInvite() { const expiresAt = expiry === "none" ? null : new Date(Date.now() + Number(expiry) * 3_600_000).toISOString(); await createInvitation(project, userId, { label, expiresAt }); setLabel(""); setMessage("Invitation created and saved."); }
  async function showQr(invite: PublicInvite) { const url = `${window.location.origin}/join/${invite.token}`; setQr({ ...qr, [invite.token]: await QRCode.toDataURL(url, { width: 260, margin: 2, color: { dark: "#22221f", light: "#fffefa" } }) }); }
  return <section className="invitations-panel"><article className="paper-panel invite-create"><h2>Create invitation</h2><label>Label <small>optional</small><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Residents association" /></label><label>Expiry<select value={expiry} onChange={(event) => setExpiry(event.target.value)}><option value="none">No expiry</option><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select></label><button className="button button-dark" onClick={() => void makeInvite()}>Create invitation</button>{message && <p role="status">{message}</p>}</article><div className="invite-list">{invites.map((invite) => <article className="paper-panel" key={invite.token}><header><div><strong>{invite.label || invite.code}</strong><small>{invite.status === "active" ? "Active" : "Revoked"}{invite.expiresAt ? ` · expires ${dateLabel(invite.expiresAt)}` : " · no expiry"}</small></div><span className={`status-${invite.status}`}>{invite.status}</span></header>{qr[invite.token] && <Image src={qr[invite.token]} width={220} height={220} unoptimized alt={`QR code for ${project.name}`} />}<div className="item-actions"><button onClick={() => void showQr(invite)}>Show QR</button><button onClick={() => void navigator.clipboard.writeText(`${window.location.origin}/join/${invite.token}`)}>Copy link</button><button onClick={() => void navigator.clipboard.writeText(invite.code)}>Copy code</button>{invite.status === "active" && <button onClick={() => void revokeInvitation(invite.token, invite.code, project.id)}>Revoke</button>}</div></article>)}{!invites.length && <p className="quiet">No invitations yet.</p>}</div></section>;
}

function RemindersManager({ project, reminders }: { project: CloudProject; reminders: Array<{ id: string; [key: string]: unknown }> }) {
  const [message, setMessage] = useState(""); const [nextRunAt, setNextRunAt] = useState(""); const [type, setType] = useState("announcement"); const [repeatType, setRepeatType] = useState<"once" | "weekly" | "fortnightly" | "monthly">("once"); const [status, setStatus] = useState("");
  const timezone = project.timezone || "Europe/London"; const previewDate = nextRunAt ? new Intl.DateTimeFormat("en-GB", { dateStyle: "full", timeStyle: "short", timeZone: timezone }).format(new Date(nextRunAt)) : "Choose a date and time";
  const upcoming = reminders.filter((reminder) => reminder.enabled !== false).sort((a, b) => (toDate(a.nextRunAt)?.getTime() || 0) - (toDate(b.nextRunAt)?.getTime() || 0));
  async function schedule(event: FormEvent) { event.preventDefault(); await createReminder(project.id, { message, nextRunAt, timezone, reminderType: type, repeatType, notifyWhen: "scheduled", category: type === "bin" ? "bins" : type === "event" ? "events" : "announcements" }); setMessage(""); setNextRunAt(""); setStatus("Reminder scheduled and added to Community Home."); }
  return <section className="reminders-v2"><header className="manage-page-heading"><div><p className="eyebrow"><span /> Community reminders</p><h2>Reminders</h2><p>Set a clear message and time. Circa shows the next reminder on Home and alerts members who have the Community open.</p></div><span className="timezone-chip">{timezone}</span></header><div className="reminder-workspace"><form className="paper-panel quick-reminder-form" onSubmit={schedule}><div className="reminder-type-buttons" aria-label="Reminder type">{[["announcement", "Announcement"], ["event", "Event"], ["bin", "Bin collection"]].map(([value, label]) => <button type="button" key={value} className={type === value ? "active" : ""} onClick={() => setType(value)}>{label}</button>)}</div><label>What should Circa remind people about?<input required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="e.g. Residents meeting starts in 30 minutes" /></label><div className="field-pair"><label>Date & time<input required type="datetime-local" value={nextRunAt} onChange={(event) => setNextRunAt(event.target.value)} /></label><label>Repeat<select value={repeatType} onChange={(event) => setRepeatType(event.target.value as typeof repeatType)}><option value="once">Once</option><option value="weekly">Weekly</option><option value="fortnightly">Every 2 weeks</option><option value="monthly">Monthly</option></select></label></div><div className="reminder-preview reminder-preview-v2"><small>Preview</small><strong>{message || "Your reminder"}</strong><span>{previewDate}</span></div><button className="button button-dark">Schedule reminder</button>{status && <p className="admin-success" role="status">{status}</p>}</form><article className="paper-panel reminder-history reminder-history-v2"><div className="admin-panel-title"><strong>Scheduled</strong><span>{upcoming.length}</span></div>{upcoming.map((reminder) => <div key={reminder.id}><span><strong>{String(reminder.message || "Reminder")}</strong><small>{reminderTimeLabel(reminder.nextRunAt, timezone)} · {String(reminder.repeatType || "once").replace(/-/g, " ")}</small></span><button className="danger-text" onClick={() => { if (window.confirm("Delete this reminder?")) void deleteReminder(project.id, reminder.id); }}>Delete</button></div>)}{!upcoming.length && <div className="admin-empty-state">No reminders scheduled yet.</div>}</article></div></section>;
}
